Updates

diff --git a/bin/casa-ms-split b/bin/casa-ms-split
--- a/bin/casa-ms-split
+++ b/bin/casa-ms-split
@@ -1207,21 +1207,21 @@ for (( ivis=0; ivis<${#CASA_INP_VIS[@]}; ivis++ )); do
                     echo "#!/usr/bin/env python"                                             > "$CASAMS_Script5"
                     echo "#!/bin/bash"                                                       > "$CASAMS_Script6"
                     
-                    echo "source \"$(dirname ${BASH_SOURCE[0]})/bin-clear-casa-path\""       >> "$CASAMS_Script6" # clear CASA path for running GILDAS
-                    echo "if [[ \$(command -v mapping | wc -l) -eq 0 ]]; then "              >> "$CASAMS_Script6" # check GILDAS mapping path
-                    echo "    if [[ -f \$HOME/Software/GILDAS/SETUP.bash ]]; then "          >> "$CASAMS_Script6" # source GILDAS from a possible path
-                    echo "        source \"\$HOME/Software/GILDAS/SETUP.bash\""              >> "$CASAMS_Script6" # source GILDAS from a possible path
-                    echo "    fi"                                                            >> "$CASAMS_Script6" # source GILDAS from a possible path
-                    echo "fi"                                                                >> "$CASAMS_Script6" # source GILDAS from a possible path
-                    echo "if [[ \$(command -v mapping | wc -l) -eq 0 ]]; then "              >> "$CASAMS_Script6" # check GILDAS
-                    echo "    echo \"Error! GILDAS mapping not found in the PATH!\""         >> "$CASAMS_Script6" # check GILDAS
-                    echo "    exit 255"                                                      >> "$CASAMS_Script6" # check GILDAS
-                    echo "fi"                                                                >> "$CASAMS_Script6" # check GILDAS
-                    echo "if [[ ! -z \$GAG_PATH ]]; then "                                   >> "$CASAMS_Script6" # re-source GILDAS to make sure it works
-                    echo "    if [[ -f \"\$GAG_PATH/bash_profile\" ]]; then "                >> "$CASAMS_Script6" # re-source GILDAS to make sure it works
-                    echo "        source \"\$GAG_PATH/bash_profile\""                        >> "$CASAMS_Script6" # re-source GILDAS to make sure it works
-                    echo "    fi"                                                            >> "$CASAMS_Script6" # re-source GILDAS to make sure it works
-                    echo "fi"                                                                >> "$CASAMS_Script6" # re-source GILDAS to make sure it works
+                    echo "source \"$(dirname ${BASH_SOURCE[0]})/bin-clear-casa-path\""                  >> "$CASAMS_Script6" # clear CASA path for running GILDAS
+                    echo "if [[ \$(echo \"say hello\" | mapping 2>/dev/null | wc -l) -eq 0 ]]; then "   >> "$CASAMS_Script6" # check GILDAS mapping path
+                    echo "    if [[ -f \$HOME/Software/GILDAS/SETUP.bash ]]; then "                     >> "$CASAMS_Script6" # source GILDAS from a possible path
+                    echo "        source \"\$HOME/Software/GILDAS/SETUP.bash\""                         >> "$CASAMS_Script6" # source GILDAS from a possible path
+                    echo "    fi"                                                                       >> "$CASAMS_Script6" # source GILDAS from a possible path
+                    echo "fi"                                                                           >> "$CASAMS_Script6" # source GILDAS from a possible path
+                    echo "if [[ ! -z \$GAG_PATH ]]; then "                                              >> "$CASAMS_Script6" # re-source GILDAS to make sure it works
+                    echo "    if [[ -f \"\$GAG_PATH/bash_profile\" ]]; then "                           >> "$CASAMS_Script6" # re-source GILDAS to make sure it works
+                    echo "        source \"\$GAG_PATH/bash_profile\""                                   >> "$CASAMS_Script6" # re-source GILDAS to make sure it works
+                    echo "    fi"                                                                       >> "$CASAMS_Script6" # re-source GILDAS to make sure it works
+                    echo "fi"                                                                           >> "$CASAMS_Script6" # re-source GILDAS to make sure it works
+                    echo "if [[ \$(echo \"say hello\" | mapping 2>/dev/null | wc -l) -eq 0 ]]; then "   >> "$CASAMS_Script6" # re-check GILDAS
+                    echo "    echo \"Error! GILDAS mapping not found in the PATH!\""                    >> "$CASAMS_Script6" # re-check GILDAS
+                    echo "    exit 255"                                                                 >> "$CASAMS_Script6" # re-check GILDAS
+                    echo "fi"                                                                           >> "$CASAMS_Script6" # re-check GILDAS
                     
                     
                     echo "import os, sys"                                                                                    >> "$CASAMS_Script1"
