Updates

diff --git a/bin/casa-ms-split b/bin/casa-ms-split
--- a/bin/casa-ms-split
+++ b/bin/casa-ms-split
@@ -145,7 +145,7 @@ for (( ivis=0; ivis<${#CASA_INP_VIS[@]}; ivis++ )); do
     echo "# This script needs to be executed by CASA as follows:"                       >  "$CASAMS_ScriptName.py"
     echo "# casa --nogui --log2term -c \"execfile('$CASAMS_ScriptName.py')\""           >> "$CASAMS_ScriptName.py"
     echo "# "                                                                           >> "$CASAMS_ScriptName.py"
-    echo "import os"                                                                    >> "$CASAMS_ScriptName.py" #<20180321>#
+    echo "import os, sys"                                                               >> "$CASAMS_ScriptName.py" #<20180321>#
     echo "import numpy"                                                                 >> "$CASAMS_ScriptName.py" #<20180321>#
     echo "import json"                                                                  >> "$CASAMS_ScriptName.py" #<20180321>#
     echo "# "                                                                           >> "$CASAMS_ScriptName.py"
@@ -346,14 +346,20 @@ for (( ivis=0; ivis<${#CASA_INP_VIS[@]}; ivis++ )); do
     echo "        vis_flag_data = tb2.getcol('FLAG')"                                                                       >> "$CASAMS_ScriptName.py"
     echo "        # "                                                                                                       >> "$CASAMS_ScriptName.py"
     echo "        # check completely flagged channels"                                                                      >> "$CASAMS_ScriptName.py"
-    echo "        vis_flag_mask = (numpy.count_nonzero(vis_flag_data, axis=1) == 0)"                                        >> "$CASAMS_ScriptName.py"
+    echo "        if len(vis_flag_data.shape) == 3:"                                                                        >> "$CASAMS_ScriptName.py"
+    echo "            vis_flag_mask = numpy.all(vis_flag_data, axis=(0,2))"                                                 >> "$CASAMS_ScriptName.py"
+    echo "        elif len(vis_flag_data.shape) == 2:"                                                                      >> "$CASAMS_ScriptName.py"
+    echo "            vis_flag_mask = numpy.all(vis_flag_data, axis=(1,))"                                                  >> "$CASAMS_ScriptName.py"
+    echo "        else:"                                                                                                    >> "$CASAMS_ScriptName.py"
+    echo "            print('Error! wrong data dimension %s!'%(str(vis_flag_data.shape)))"                                  >> "$CASAMS_ScriptName.py"
+    echo "            sys.exit()"                                                                                           >> "$CASAMS_ScriptName.py"
     echo "        # "                                                                                                       >> "$CASAMS_ScriptName.py"
     echo "        # It seems writting each channel number seperately will cause CASA not able to work properly, "           >> "$CASAMS_ScriptName.py"
     echo "        # so we have to merge consecutive channels and write them into channel ranges, "                          >> "$CASAMS_ScriptName.py"
     echo "        # e.g., write [0,1,2,3,60,61,62,63] as '0~3;60~63'"                                                       >> "$CASAMS_ScriptName.py"
     echo "        # Our way is to check each element whether its difference to left and right elements are both 1."         >> "$CASAMS_ScriptName.py"
     echo "        if numpy.count_nonzero(vis_flag_mask) > 0:"                                                               >> "$CASAMS_ScriptName.py"
-    echo "            vis_chan_flagged = numpy.arange(vis_flag_mask)[vis_flag_mask]"                                        >> "$CASAMS_ScriptName.py"
+    echo "            vis_chan_flagged = numpy.arange(len(vis_flag_mask))[vis_flag_mask]"                                   >> "$CASAMS_ScriptName.py"
     echo "            if len(vis_chan_flagged) == 1:"                                                                       >> "$CASAMS_ScriptName.py"
     echo "                vis_chan_flagged_str = '%d'%(vis_chan_flagged)"                                                   >> "$CASAMS_ScriptName.py"
     echo "            else:"                                                                                                >> "$CASAMS_ScriptName.py"
@@ -375,7 +381,7 @@ for (( ivis=0; ivis<${#CASA_INP_VIS[@]}; ivis++ )); do
     echo "                                                 )])"                                                             >> "$CASAMS_ScriptName.py"
     echo "        # "                                                                                                       >> "$CASAMS_ScriptName.py"
     echo "        if numpy.count_nonzero(~vis_flag_mask) > 0:"                                                              >> "$CASAMS_ScriptName.py"
-    echo "            vis_chan_nonflagged = numpy.arange(vis_flag_mask)[~vis_flag_mask]"                                    >> "$CASAMS_ScriptName.py"
+    echo "            vis_chan_nonflagged = numpy.arange(len(vis_flag_mask))[~vis_flag_mask]"                               >> "$CASAMS_ScriptName.py"
     echo "            if len(vis_chan_nonflagged) == 1:"                                                                    >> "$CASAMS_ScriptName.py"
     echo "                vis_chan_nonflagged_str = '%d'%(vis_chan_nonflagged)"                                             >> "$CASAMS_ScriptName.py"
     echo "            else:"                                                                                                >> "$CASAMS_ScriptName.py"
@@ -535,7 +541,12 @@ for (( ivis=0; ivis<${#CASA_INP_VIS[@]}; ivis++ )); do
     
     $CASA_COMMAND --nogui --log2term -c "$CASAMS_ScriptName.py" > "$CASAMS_ScriptName.log" 2>&1
     
-    echo "Finished casa!"
+    if [[ $(cat "$CASAMS_ScriptName.log" | grep -i "Error" | wc -l) -gt 0 ]]; then
+        echo "Error! Failed to run \"$CASAMS_ScriptName.py\" in CASA! Please check \"$CASAMS_ScriptName.log\"!"
+        exit 255
+    else
+        echo "Finished running \"$CASAMS_ScriptName.py\" in CASA!"
+    fi
     
     # 
     # Read data tables
