Updates

diff --git a/bin/pdbi-uvt-go-uvcont b/bin/pdbi-uvt-go-uvcont
--- a/bin/pdbi-uvt-go-uvcont
+++ b/bin/pdbi-uvt-go-uvcont
@@ -61,7 +61,10 @@ if [[ ${#PdBIUVT_VWID[@]} -gt 0 ]] && [[ ${#PdBIUVT_FCEN[@]} -gt 0 ]]; then
     check_has_input_line=1
 fi
 check_has_input=$((check_has_input_range+check_has_input_line))
-if [[ ${#PdBIUVT_NAME[@]} -eq 0 ]] || [[ $check_has_input -eq 0 ]]; then
+#if [[ $check_has_input -eq 0 ]]; then 
+#    # if nothing is input for crange or linefreq, then set crange to 0 0
+#fi
+if [[ ${#PdBIUVT_NAME[@]} -eq 0 ]]; then
     usage; exit
 fi
 
@@ -74,16 +77,18 @@ for (( tk=0; tk<${#PdBIUVT_NAME[@]}; tk++ )); do
     
     
     
-    # 
-    # SOURCE pdbi-uvt-core-cvf
-    # 
-    if [[ -f $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-cvf-v10" ]]; then
-        source $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-cvf-v10" "${PdBIUVT_NAME[tk]}.${PdBIUVT_TYPE[tk]}"
-    else
-        echo ""
-        echo "Error! Could not find \""$(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-cvf-v10\"!"
-        echo ""
-        exit 1
+    if [[ $check_has_input -gt 0 ]]; then 
+        # 
+        # SOURCE pdbi-uvt-core-cvf
+        # 
+        if [[ -f $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-cvf-v10" ]]; then
+            source $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-cvf-v10" "${PdBIUVT_NAME[tk]}.${PdBIUVT_TYPE[tk]}"
+        else
+            echo ""
+            echo "Error! Could not find \""$(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-cvf-v10\"!"
+            echo ""
+            exit 1
+        fi
     fi
     
     
