Updates

diff --git a/bin/pdbi-uvt-go-average b/bin/pdbi-uvt-go-average
--- a/bin/pdbi-uvt-go-average
+++ b/bin/pdbi-uvt-go-average
@@ -1,125 +1,174 @@
 #!/bin/bash
 # 
 # Input UV table file name
-# Output spec & uv_average
+# Output uv averaged single channel uv data table
+# 
+# Last update:
+#    2017-03-30 using "pdbi-uvt-core-arg-v5"
 # 
 # 
-# Usage
+
+
+
 # 
-PdBIUVT_PrintUsage() {
+# Uage
+# 
+usage() {
     echo "Usage: "
     echo "    pdbi-uvt-go-average -name PdBIUVT_NAME -crange 1 50 55 90 [-out PdBIUVT_NAME-Averaged]"
     echo "    pdbi-uvt-go-average -name PdBIUVT_NAME -linefreq 89.098 -linewidth 450 [-out PdBIUVT_NAME-Averaged]"
     echo "    pdbi-uvt-go-average -name PdBIUVT_NAME -redshift 2.055 -linename \"CO(3-2)\" -linewidth 450 [-out PdBIUVT_NAME-Averaged]"
+    echo ""
 }
-if [[ $# -eq 0 ]]; then
-    PdBIUVT_PrintUsage
-    exit
-fi
+
+
+
 # 
-# LANG
+# SOURCE pdbi-uvt-core-arg
 # 
-LANG=C
-#
-# readlink
-# 
-if [[ $(uname) == *"Darwin"* ]]; then
-    function readlink() {
-        if [[ $# -gt 1 ]]; then if [[ "$1" == "-f" ]]; then shift; fi; fi
-        DIR=$(echo "${1%/*}"); (cd "$DIR" && echo "$(pwd -P)/$(basename ${1})")
-    }
-fi
-PdBIUVT_DIR=$(dirname $(readlink -f "${BASH_SOURCE[0]}"))
-# 
-# Call pdbi-uvt-core-cvf
-# 
-if [[ -f "$PdBIUVT_DIR/pdbi-uvt-core-cvf" ]]; then
-    source "$PdBIUVT_DIR/pdbi-uvt-core-cvf" "$@"
+if [[ -f $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5" ]]; then
+    source $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5" "$@"
 else
-    echo ""; echo "Error! Could not find \"$PdBIUVT_DIR/pdbi-uvt-core-cvf\"!"; echo ""
-    exit
+    echo ""
+    echo "Error! Could not find \""$(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5\"!"
+    echo ""
+    exit 1
 fi
 
 
 
 # 
+# Check input parameters -- uvt file name
 # 
-# 
-echo ""
-
-
-
-# 
-# Check output file
-# 
-# -- set output uvtable name, and check whether it exists
-if [[ x"$PdBIUVT_SAVE" == x"" || x"$PdBIUVT_SAVE" == x"tmp_pdbi_uvt" ]]; then
-    echo "Warning! Output uv table name not defined, we will set it to be ${PdBIUVT_NAME[0]}-Averaged.uvt!"
-    PdBIUVT_SAVE="${PdBIUVT_NAME[0]}-Averaged"
-fi
-if [[ -f "$PdBIUVT_SAVE.uvt" ]]; then
-    echo "Warning! Found previous \"$PdBIUVT_SAVE.uvt\"! Backup as \"$PdBIUVT_SAVE.uvt.backup\"!"
-    cp "$PdBIUVT_SAVE.uvt" "$PdBIUVT_SAVE.uvt.backup"
+if [[ ${#PdBIUVT_NAME[@]} -eq 0 ]]; then
+    usage; exit
 fi
 
 
 
 # 
-# Check CRANGE list
+# Loop input uv tables
 # 
-if [[ ${#PdBIUVT_CMIN[@]} -eq 0 || ${#PdBIUVT_CMAX[@]} -eq 0 || ${#PdBIUVT_CMIN[@]} != ${#PdBIUVT_CMAX[@]} ]]; then
-    PdBIUVT_PrintUsage
-    exit
-fi
-
-# 
-# Prepare CRANGE list
-# 
-for (( i=0; i<1; i++ )); do
-    if [[ ${PdBIUVT_CMIN[i]} -gt 0 && ${PdBIUVT_CMAX[i]} -gt 0 ]]; then
-        PdBIUVT_CAGE="${PdBIUVT_CMIN[i]} ${PdBIUVT_CMAX[i]}"
+for (( tk=0; tk<${#PdBIUVT_NAME[@]}; tk++ )); do
+    
+    
+    
+    # 
+    # SOURCE pdbi-uvt-core-cvf
+    # 
+    if [[ -f $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-cvf-v5" ]]; then
+        source $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-cvf-v5" "${PdBIUVT_NAME[tk]}.${PdBIUVT_TYPE[tk]}"
+    else
+        echo ""
+        echo "Error! Could not find \""$(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-cvf-v5\"!"
+        echo ""
+        exit 1
+    fi
+    
+    
+    
+    # 
+    # Check input parameters -- crange
+    # 
+    if [[ ${#PdBIUVT_CMIN[@]} -le 0 || ${#PdBIUVT_CMAX[@]} -le 0 ]]; then
+        echo ""; echo "Error! Could not determine channel range for the input uv table \"${PdBIUVT_NAME[tk]}.${PdBIUVT_TYPE[tk]}\"! Please check your input e.g. \"-crange 0 0\"!"; echo ""
+        continue
+    fi
+    
+    
+    
+    # 
+    # Set default output file
+    # 
+    if [[ ${#PdBIUVT_SAVE[@]} -le $tk ]]; then
+        PdBIUVT_SAVE+=($(basename "${PdBIUVT_NAME[tk]}")"-Averaged")
+        echo ""; echo "Warning! Output name was not defined, we will set it as \"${PdBIUVT_SAVE[tk]}\"!"; echo ""
+    fi
+    if [[ x"${PdBIUVT_SAVE[tk]}" == x || x"${PdBIUVT_SAVE[tk]}" == x"tmp_pdbi_uvt" || x"${PdBIUVT_SAVE[tk]}" == x"tmp_pdbi_uvt_run_uv_fit" ]]; then
+        PdBIUVT_SAVE[tk]=$(basename "${PdBIUVT_NAME[tk]}")"-Averaged"
+        echo ""; echo "Warning! Output name was not defined, we will set it as \"${PdBIUVT_SAVE[tk]}\"!"; echo ""
+    fi
+    # 
+    # Remove suffix
+    # 
+    if [[ x"${PdBIUVT_SAVE[tk]}" == x*".uvt" ]]; then
+        PdBIUVT_SAVE[tk]=$(echo "${PdBIUVT_SAVE[tk]}" | sed -e 's/\.uvt$//g')
+    fi
+    if [[ x"${PdBIUVT_SAVE[tk]}" == x*".UVT" ]]; then
+        PdBIUVT_SAVE[tk]=$(echo "${PdBIUVT_SAVE[tk]}" | sed -e 's/\.UVT$//g')
+    fi
+    # 
+    # Backup existing output file
+    # 
+    if [[ -f "${PdBIUVT_SAVE[tk]}.uvt" ]]; then
+        echo "Warning! Found existing \"${PdBIUVT_SAVE[tk]}.uvt\"! Backup as \"${PdBIUVT_SAVE[tk]}.uvt.backup\"!"
+        mv "${PdBIUVT_SAVE[tk]}.uvt" "${PdBIUVT_SAVE[tk]}.uvt.backup"
+    fi
+    
+    
+    
+    # 
+    # Deal with the input uv data file
+    # 
+    # Prepare CRANGE list
+    # 
+    if [[ ${PdBIUVT_CMIN[0]} -gt 0 && ${PdBIUVT_CMAX[0]} -gt 0 ]]; then
+        PdBIUVT_CAGE="${PdBIUVT_CMIN[0]} ${PdBIUVT_CMAX[0]}"
     else
         PdBIUVT_CAGE="$PdBIUVT_CHAN_MIN $PdBIUVT_CHAN_MAX"
     fi
-done
-for (( i=1; i<${#PdBIUVT_CMIN[@]}; i++ )); do
-    if [[ ${PdBIUVT_CMIN[i]} -gt 0 && ${PdBIUVT_CMAX[i]} -gt 0 ]]; then
-        PdBIUVT_CAGE="$PdBIUVT_CAGE ${PdBIUVT_CMIN[i]} ${PdBIUVT_CMAX[i]}"
-        ##echo "CRANGE: $PdBIUVT_CAGE"
+    for (( i=1; i<${#PdBIUVT_CMIN[@]}; i++ )); do
+        if [[ ${PdBIUVT_CMIN[i]} -gt 0 && ${PdBIUVT_CMAX[i]} -gt 0 ]]; then
+            PdBIUVT_CAGE="$PdBIUVT_CAGE ${PdBIUVT_CMIN[i]} ${PdBIUVT_CMAX[i]}"
+        fi
+    done
+    echo ""
+    echo "CRANGE: $PdBIUVT_CAGE"
+    echo ""
+    # 
+    # prepare gildas/mapping init and script and run
+    # 
+    PdBIUVT_TEMP_INIT="${PdBIUVT_NAME[tk]}.${PdBIUVT_TYPE[tk]}.uv_average.init"
+    PdBIUVT_TEMP_EXEC="${PdBIUVT_NAME[tk]}.${PdBIUVT_TYPE[tk]}.uv_average.map"
+    PdBIUVT_TEMP_LOGT="${PdBIUVT_NAME[tk]}.${PdBIUVT_TYPE[tk]}.uv_average.log"
+    echo  '! '                                                                                          >  $PdBIUVT_TEMP_INIT
+    echo  '! Task UV_AVERAGE'                                                                           >> $PdBIUVT_TEMP_INIT
+    echo  '!'                                                                                           >> $PdBIUVT_TEMP_INIT
+    echo  'TASK\CHARACTER "Input UV table"    UV_INPUT$  "'"${PdBIUVT_NAME[tk]}.${PdBIUVT_TYPE[tk]}"'"' >> $PdBIUVT_TEMP_INIT
+    echo  'TASK\CHARACTER "Output UV table"  UV_OUTPUT$  "'"${PdBIUVT_SAVE[tk]}.uvt"'"'                 >> $PdBIUVT_TEMP_INIT
+    echo  'TASK\VALUES    "Channel range"       RANGES$   '"$PdBIUVT_CAGE"                              >> $PdBIUVT_TEMP_INIT
+    echo  'TASK\CHARACTER "Type of range"        CTYPE$  "'"CHANNEL"'"'                                 >> $PdBIUVT_TEMP_INIT
+    echo  'TASK\GO'                                                                                     >> $PdBIUVT_TEMP_INIT
+    echo  "run uv_average $PdBIUVT_TEMP_INIT /NOWINDOW" > $PdBIUVT_TEMP_EXEC
+    echo  "@$PdBIUVT_TEMP_EXEC | mapping > $PdBIUVT_TEMP_LOGT"
+    echo  "@$PdBIUVT_TEMP_EXEC" | mapping > "$PdBIUVT_TEMP_LOGT"
+    # 
+    if [[ -f "${PdBIUVT_SAVE[tk]}.uvt" ]]; then
+        echo "Successufully saved to \"${PdBIUVT_SAVE[tk]}.uvt\"!"
+        echo "--"
+        if [[ -f "$PdBIUVT_TEMP_LOGT" ]]; then
+            rm "$PdBIUVT_TEMP_LOGT"
+        fi
+    else
+        echo "Error! Failed to run GILDAS MAPPING UV_SUBTRACT and output \"${PdBIUVT_SAVE[tk]}.uvt\"!"
+        echo "Please check \"$PdBIUVT_TEMP_LOGT\"!"
+        exit 1
     fi
+    
+    
 done
-echo ""
-echo "CRANGE: $PdBIUVT_CAGE"
-echo ""
-# 
-# prepare gildas/mapping init and script and run
-# 
-PdBIUVT_TEMP_INIT="tmp_doUVAVERAGE.init"
-PdBIUVT_TEMP_EXEC="tmp_doUVAVERAGE.map"
-PdBIUVT_TEMP_LOGT="tmp_doUVAVERAGE.log"
-echo  '! '                                                                                       > $PdBIUVT_TEMP_INIT
-echo  '! Task UV_AVERAGE'                                                                       >> $PdBIUVT_TEMP_INIT
-echo  '! 6 parameters needed for all functions'                                                 >> $PdBIUVT_TEMP_INIT
-echo  '!'                                                                                       >> $PdBIUVT_TEMP_INIT
-echo  'TASK\CHARACTER "Input UV table"                   UV_INPUT$      "'$PdBIUVT_NAME'.uvt"'  >> $PdBIUVT_TEMP_INIT
-echo  'TASK\CHARACTER "Output UV table"                  UV_OUTPUT$     "'$PdBIUVT_SAVE'.uvt"'  >> $PdBIUVT_TEMP_INIT
-echo  'TASK\VALUES    "Channel range"                    RANGES$         '$PdBIUVT_CAGE         >> $PdBIUVT_TEMP_INIT
-echo  'TASK\CHARACTER "Type of range"                    CTYPE$         "'"CHANNEL"'"'          >> $PdBIUVT_TEMP_INIT
-echo  'TASK\GO'                                                                                 >> $PdBIUVT_TEMP_INIT
-echo  "let name $PdBIUVT_NAME"                        > $PdBIUVT_TEMP_EXEC
-echo  "let type lmv"                                 >> $PdBIUVT_TEMP_EXEC
-#echo  "let size $PdBIUVT_SIZE"                       >> $PdBIUVT_TEMP_EXEC
-echo  "run uv_average $PdBIUVT_TEMP_INIT /NOWINDOW"  >> $PdBIUVT_TEMP_EXEC
-echo  '@tmp_doUVAVERAGE.map  |  mapping  > '"$PdBIUVT_TEMP_LOGT"
-echo  '@tmp_doUVAVERAGE.map' |  mapping  >  "$PdBIUVT_TEMP_LOGT"
-# 
-# 
-echo 
-tail -n 1 "$PdBIUVT_TEMP_LOGT"
-echo "I-RUN,  Output to $PdBIUVT_SAVE.uvt"
-echo 
 
-cp "$PdBIUVT_TEMP_INIT" "$PdBIUVT_SAVE.init"
-cp "$PdBIUVT_TEMP_EXEC" "$PdBIUVT_SAVE.map"
-cp "$PdBIUVT_TEMP_LOGT" "$PdBIUVT_SAVE.log"
+
+
+
+
+
+
+
+
+
+
+
+
+
 
diff --git a/bin/pdbi-uvt-go-compress b/bin/pdbi-uvt-go-compress
--- a/bin/pdbi-uvt-go-compress
+++ b/bin/pdbi-uvt-go-compress
@@ -3,118 +3,134 @@
 # Input uvtablefile and average channel width
 # Output compressed uvtablefile
 # 
-PdBIUVT_NAME=()
-PdBIUVT_SAVE=()
-PdBIUVT_WCHN=() # the average channel width
-PdBIUVT_SIZE="" # useless here
-# LANG
-LANG=C
-
+# Last update:
+#    2017-03-30 using "pdbi-uvt-core-arg-v5"
+# 
+# 
 
 
 
 # 
-# Read input parameters
+# Uage
 # 
-PdBIUVT_GOOD=0; if [[ "$#" -gt 0 ]]; then PdBIUVT_GOOD=1; fi
-PdBIUVT_RPAR=""
-while [[ "$#" -gt 0 ]]; do
-    #echo $1 "$#"
-    case $1 in
-          "-size") if [[ "$#" -lt 2 ]]; then PdBIUVT_GOOD=0; break; fi; shift; PdBIUVT_RPAR=""; PdBIUVT_SIZE="$1";;
-          "-name") if [[ "$#" -lt 2 ]]; then PdBIUVT_GOOD=0; break; fi; shift; PdBIUVT_RPAR="name";;
-          "-save") if [[ "$#" -lt 2 ]]; then PdBIUVT_GOOD=0; break; fi; shift; PdBIUVT_RPAR="save";;
-           "-out") if [[ "$#" -lt 2 ]]; then PdBIUVT_GOOD=0; break; fi; shift; PdBIUVT_RPAR="save";;
-         "-width") if [[ "$#" -lt 2 ]]; then PdBIUVT_GOOD=0; break; fi; shift; PdBIUVT_RPAR="chanwidth";;
-    esac
-    if [[ "$PdBIUVT_RPAR" == "name" ]];  then 
-        PdBIUVT_NAME=("${PdBIUVT_NAME[@]}" "$1")
-    fi
-    if [[ "$PdBIUVT_RPAR" == "save" ]];  then 
-        PdBIUVT_SAVE=("${PdBIUVT_SAVE[@]}" "$1")
-    fi
-    if [[ "$PdBIUVT_RPAR" == "chanwidth" ]];  then 
-        PdBIUVT_WCHN=("${PdBIUVT_WCHN[@]}" "$1")
-    fi
-    shift
-done
-# 
-# Check input parameters -- if not passed then print usage and exit
-# 
-if [[ $PdBIUVT_GOOD -eq 0 ]]; then
+usage() {
     echo "Usage: "
-    echo "   pdbi-uvt-go-compress -name UV_TABLE_NAME_1 -width 8 -out UV_TABLE_NEW"
-    exit
-fi
+    echo "  pdbi-uvt-go-compress -name UV_TABLE_NAME_1 -width 8 -out UV_TABLE_NEW"
+    echo ""
+}
+
+
+
 # 
-# Print input uvtable list
+# SOURCE pdbi-uvt-core-arg
 # 
-echo PdBIUVT_NAME=${PdBIUVT_NAME[*]}
-echo PdBIUVT_SAVE=${PdBIUVT_SAVE[*]}
-# 
-# Revise input parameters
-# 
-for (( PdBIUVT_ITER = 0; PdBIUVT_ITER < "${#PdBIUVT_NAME[@]}"; PdBIUVT_ITER++ )); do
-    # -- remove the suffix of the input uvtable name, and test whether the file exists
-    if [[ "${PdBIUVT_NAME[$PdBIUVT_ITER]}" == *".uvt" ]]; then
-        PdBIUVT_NAME[$PdBIUVT_ITER]=$(echo "${PdBIUVT_NAME[$PdBIUVT_ITER]}" | sed -E 's/[.]uvt$//g')
-    fi
-    if [[ ! -f "${PdBIUVT_NAME[$PdBIUVT_ITER]}.uvt" ]]; then
-        echo "Error! \"${PdBIUVT_NAME[$PdBIUVT_ITER]}.uvt\" was not found! Exit!"
-        exit
-    fi
-    # -- set output uvtable name, and check whether it exists
-    if [[ ${#PdBIUVT_SAVE[@]} -le $PdBIUVT_ITER ]]; then
-        echo "Warning! Output uv table name not defined, we will set the output file as ${PdBIUVT_NAME[$PdBIUVT_ITER]}-Compressed.uvt!"
-        PdBIUVT_SAVE=(${PdBIUVT_SAVE[@]} ${PdBIUVT_NAME[$PdBIUVT_ITER]}-Compressed)
-    fi
-    if [[ "${PdBIUVT_SAVE[$PdBIUVT_ITER]}" == *".uvt" ]]; then
-        PdBIUVT_SAVE[$PdBIUVT_ITER]=$(echo ${PdBIUVT_SAVE[$PdBIUVT_ITER]} | sed -E 's/[.]uvt$//g')
-    fi
-    # TODO will overwrite, give warning?
-done
-# -- check output uvt name
-if [[ ${#PdBIUVT_SAVE[@]} -eq 0 ]]; then
-    echo "Error! Output uv table name not defined!"
-    exit 1
-fi
-if [[ ${#PdBIUVT_SAVE[@]} -ne ${#PdBIUVT_NAME[@]} ]]; then
-    echo "Error! Output uv table number does not match the input uv table number!"
-    exit 1
-fi
-if [[ ${#PdBIUVT_WCHN[@]} -ne ${#PdBIUVT_NAME[@]} ]]; then
-    echo "Error! The input channel width number does not match the input uv table number!"
+if [[ -f $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5" ]]; then
+    source $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5" "$@"
+else
+    echo ""
+    echo "Error! Could not find \""$(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5\"!"
+    echo ""
     exit 1
 fi
 
 
 
 # 
-# loop input uv tables to compress each of them
+# Check input parameters -- uvt file name, ra dec
 # 
-for (( PdBIUVT_ITER = 0; PdBIUVT_ITER < "${#PdBIUVT_NAME[@]}"; PdBIUVT_ITER++ )); do
+if [[ ${#PdBIUVT_NAME[@]} -eq 0 || ${#PdBIUVT_UVCOMPRESS_NC[@]} -eq 0 ]]; then
+    usage; exit
+fi
+
+
+
+# 
+# Loop input uv tables
+# 
+for (( i = 0; i < "${#PdBIUVT_NAME[@]}"; i++ )); do
     # 
-    # prepare gildas/mapping init and script and run
+    # if type is uvtable
     # 
-    # 
-    PdBIUVT_TEMP_INIT="${PdBIUVT_SAVE[$PdBIUVT_ITER]}.init"
-    PdBIUVT_TEMP_EXEC="${PdBIUVT_SAVE[$PdBIUVT_ITER]}.map"
-    PdBIUVT_TEMP_LOGT="${PdBIUVT_SAVE[$PdBIUVT_ITER]}.log"
-    echo  '! '                                                                                               > $PdBIUVT_TEMP_INIT
-    echo  '! Task UV_COMPRESS'                                                                              >> $PdBIUVT_TEMP_INIT
-    echo  '! 3 parameters needed for all functions'                                                         >> $PdBIUVT_TEMP_INIT
-    echo  '!'                                                                                               >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\CHARACTER "UV table 1"                  UV_INPUT$      "'${PdBIUVT_NAME[$PdBIUVT_ITER]}'"'  >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\CHARACTER "UV table out"               UV_OUTPUT$      "'${PdBIUVT_SAVE[$PdBIUVT_ITER]}'"'  >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\INTEGER   "Channel width"                     NC$       ' ${PdBIUVT_WCHN[$PdBIUVT_ITER]}    >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\GO'                                                                                         >> $PdBIUVT_TEMP_INIT
-    echo  "run uv_compress $PdBIUVT_TEMP_INIT /NOWINDOW"  >> $PdBIUVT_TEMP_EXEC
-    echo  "@$PdBIUVT_TEMP_EXEC  |  mapping  > ""$PdBIUVT_TEMP_LOGT"
-    echo  "@$PdBIUVT_TEMP_EXEC" |  mapping  >  "$PdBIUVT_TEMP_LOGT"
+    if [[ ${PdBIUVT_TYPE[i]} == "uvt" || ${PdBIUVT_TYPE[i]} == "UVT" ]]; then
+        # 
+        # Set default output file name
+        # 
+        if [[ ${#PdBIUVT_SAVE[@]} -le $i ]]; then
+            PdBIUVT_SAVE+=("${PdBIUVT_NAME[i]}-Compressed")
+        fi
+        if [[ x"${PdBIUVT_SAVE[i]}" == x || x"${PdBIUVT_SAVE[i]}" == x"tmp_pdbi_uvt" ]]; then 
+            PdBIUVT_SAVE[i]="${PdBIUVT_NAME[i]}-Compressed"
+            echo ""; echo "Warning! Output name was not given for the input uvtable \"${PdBIUVT_NAME[i]}\", setting to \"${PdBIUVT_SAVE[i]}\""; echo ""
+        fi
+        # 
+        # Remove suffix
+        # 
+        if [[ x"${PdBIUVT_SAVE[i]}" == x*".uvt" ]]; then
+            PdBIUVT_SAVE[i]=$(echo "${PdBIUVT_SAVE[i]}" | sed -e 's/\.uvt$//g')
+        fi
+        if [[ x"${PdBIUVT_SAVE[i]}" == x*".UVT" ]]; then
+            PdBIUVT_SAVE[i]=$(echo "${PdBIUVT_SAVE[i]}" | sed -e 's/\.UVT$//g')
+        fi
+        # 
+        # Backup existing output file
+        # 
+        if [[ -f "${PdBIUVT_SAVE[i]}.uvt" ]]; then
+            echo "Warning! Found existing \"${PdBIUVT_SAVE[i]}.uvt\"! Backup as \"${PdBIUVT_SAVE[i]}.uvt.backup\"!"
+            mv "${PdBIUVT_SAVE[i]}.uvt" "${PdBIUVT_SAVE[i]}.uvt.backup"
+        fi
+        # 
+        # check input channel width
+        # 
+        if [[ ${#PdBIUVT_UVCOMPRESS_NC[@]} -le $i ]]; then
+            TEMP_NC="${PdBIUVT_UVCOMPRESS_NC[${#PdBIUVT_UVCOMPRESS_NC[@]}-1]}" # repeat the last input channel width if the input channel width number is less than uvtable number
+        else
+            TEMP_NC="${PdBIUVT_UVCOMPRESS_NC[i]}"
+        fi
+        # 
+        # prepare gildas/mapping init and script and run
+        # 
+        # 
+        PdBIUVT_TEMP_INIT="${PdBIUVT_SAVE[i]}.init"
+        PdBIUVT_TEMP_EXEC="${PdBIUVT_SAVE[i]}.map"
+        PdBIUVT_TEMP_LOGT="${PdBIUVT_SAVE[i]}.log"
+        echo  '! '                                                                                               > $PdBIUVT_TEMP_INIT
+        echo  '! Task UV_COMPRESS'                                                                              >> $PdBIUVT_TEMP_INIT
+        echo  '! 3 parameters needed for all functions'                                                         >> $PdBIUVT_TEMP_INIT
+        echo  '!'                                                                                               >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\CHARACTER "UV table 1"                  UV_INPUT$      "'${PdBIUVT_NAME[i]}'"'              >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\CHARACTER "UV table out"               UV_OUTPUT$      "'${PdBIUVT_SAVE[i]}'"'              >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\INTEGER   "Channel width"                     NC$       ' ${TEMP_NC}                        >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\GO'                                                                                         >> $PdBIUVT_TEMP_INIT
+        echo  "run uv_compress $PdBIUVT_TEMP_INIT /NOWINDOW" > $PdBIUVT_TEMP_EXEC
+        echo  "@$PdBIUVT_TEMP_EXEC | mapping > $PdBIUVT_TEMP_LOGT"
+        echo  "@$PdBIUVT_TEMP_EXEC" | mapping > "$PdBIUVT_TEMP_LOGT"
+        
+        if [[ -f "${PdBIUVT_SAVE[i]}.uvt" ]]; then
+            echo "Successufully saved to \"${PdBIUVT_SAVE[i]}.uvt\"!"
+            echo "--"
+            if [[ -f "$PdBIUVT_TEMP_LOGT" ]]; then
+                rm "$PdBIUVT_TEMP_LOGT"
+            fi
+        else
+            echo "Error! Failed to run GILDAS MAPPING UV_SUBTRACT and output \"${PdBIUVT_SAVE[i]}.uvt\"!"
+            echo "Please check \"$PdBIUVT_TEMP_LOGT\"!"
+            exit 1
+        fi
     
-    echo "Successufully saved to ${PdBIUVT_SAVE[$PdBIUVT_ITER]}.uvt"
+    fi
     
 done
+
+
+
+
+
+
+
+
+
+
+
 
 
 
diff --git a/bin/pdbi-uvt-go-import-uvfits b/bin/pdbi-uvt-go-import-uvfits
--- a/bin/pdbi-uvt-go-import-uvfits
+++ b/bin/pdbi-uvt-go-import-uvfits
@@ -24,122 +24,126 @@ fi
 # 
 usage() {
     echo "Usage: "
-    echo "  pdbi-uvt-go-import-uvfits -name PdBIUVT_NAME.uvt -size 15 -map_size 512 -map_cell 0.2 -out aaa.eps -overwrite"
+    echo "  pdbi-uvt-go-import-uvfits -name NAME.uvfits [NAME_2.uvfits [NAME_3.fits]]"
     echo ""
 }
 
 
 
-#
-# readlink
 # 
-if [[ $(uname) == *"Darwin"* ]]; then
-    function readlink() {
-        if [[ $# -gt 1 ]]; then if [[ "$1" == "-f" ]]; then shift; fi; fi
-        DIR=$(echo "${1%/*}"); (cd "$DIR" && echo "$(pwd -P)/$(basename ${1})")
-    }
-fi
-PdBIUVT_DIR=$(dirname $(readlink -f "${BASH_SOURCE[0]}"))
-
-
-
+# SOURCE pdbi-uvt-core-arg
 # 
-# Read input parameters by calling "pdbi-uvt-core-arg-v4"
-# 
-if [[ -f "$PdBIUVT_DIR/pdbi-uvt-core-arg-v4" ]]; then
-    source "$PdBIUVT_DIR/pdbi-uvt-core-arg-v4" "$@"
+if [[ -f $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5" ]]; then
+    source $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5" "$@"
 else
-    echo ""; echo "Error! Could not find \"$PdBIUVT_DIR/pdbi-uvt-core-arg-v4\"! Please contact software supplier!"; echo ""
-    exit
+    echo ""
+    echo "Error! Could not find \""$(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5\"!"
+    echo ""
+    exit 1
 fi
 
 
 
 # 
-# Check input parameters -- uvt file name
+# Check input parameters -- uvt file name, ra dec
 # 
-if [[ x"$PdBIUVT_NAME" == x ]]; then
+if [[ ${#PdBIUVT_NAME[@]} -eq 0 ]]; then
     usage; exit
 fi
 
 
 
-
-
-
-
-
-
-
-
 # 
-# Set default output file as
-# "$PdBIUVT_SAVE.uvt.go.uvmap.eps"
+# Loop input uv fits
 # 
-if [[ x"$PdBIUVT_SAVE" == x || x"$PdBIUVT_SAVE" == x"tmp_pdbi_uvt" ]]; then 
-    PdBIUVT_SAVE="$PdBIUVT_NAME"
-    echo ""; echo "Warning! Output name was not given, setting to \"$PdBIUVT_SAVE.uvt\""; echo ""
-fi
+for (( i = 0; i < "${#PdBIUVT_NAME[@]}"; i++ )); do
+    # 
+    # if type is uvfits
+    # 
+    if [[ ${PdBIUVT_TYPE[i]} == "uvfits" || ${PdBIUVT_TYPE[i]} == "UVFITS" || ${PdBIUVT_TYPE[i]} == "fits" || ${PdBIUVT_TYPE[i]} == "FITS" ]]; then
+        # 
+        # Set default output file name
+        # 
+        if [[ ${#PdBIUVT_SAVE[@]} -le $i ]]; then
+            PdBIUVT_SAVE+=("${PdBIUVT_NAME[i]}")
+        fi
+        if [[ x"${PdBIUVT_SAVE[i]}" == x || x"${PdBIUVT_SAVE[i]}" == x"tmp_pdbi_uvt" ]]; then 
+            PdBIUVT_SAVE[i]="${PdBIUVT_NAME[i]}"
+            echo ""; echo "Warning! Output name was not given for the input uvfits \"${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}\", setting to \"${PdBIUVT_SAVE[i]}.uvt\""; echo ""
+        fi
+        # 
+        # Remove suffix
+        # 
+        if [[ x"${PdBIUVT_SAVE[i]}" == x*".uvt" ]]; then
+            PdBIUVT_SAVE[i]=$(echo "${PdBIUVT_SAVE[i]}" | sed -e 's/\.uvt$//g')
+        fi
+        if [[ x"${PdBIUVT_SAVE[i]}" == x*".UVT" ]]; then
+            PdBIUVT_SAVE[i]=$(echo "${PdBIUVT_SAVE[i]}" | sed -e 's/\.UVT$//g')
+        fi
+        # 
+        # Backup existing output file
+        # 
+        if [[ -f "${PdBIUVT_SAVE[i]}.uvt" ]]; then
+            echo "Warning! Found existing \"${PdBIUVT_SAVE[i]}.uvt\"! Backup as \"${PdBIUVT_SAVE[i]}.uvt.backup\"!"
+            mv "${PdBIUVT_SAVE[i]}.uvt" "${PdBIUVT_SAVE[i]}.uvt.backup"
+        fi
+        # 
+        # Deal with the input uvfits file
+        # Output to mapping script
+        # "${PdBIUVT_SAVE[i]}.uvt.import.uvfits.script"
+        # 
+        PdBIUVT_EXE="${PdBIUVT_SAVE[i]}.uvt.import.uvfits.script"
+        PdBIUVT_LOG="${PdBIUVT_SAVE[i]}.uvt.import.uvfits.log"
+        PdBIUVT_INI="${PdBIUVT_SAVE[i]}.uvt.import.uvfits.init"
+        PdBIUVT_GETHEAD="${PdBIUVT_SAVE[i]}.uvt.import.uvfits.gethead"
+        PdBIUVT_SETHEAD="${PdBIUVT_SAVE[i]}.uvt.import.uvfits.sethead"
+        
+        echo "" >  "$PdBIUVT_EXE"
+        
+        echo "Checking \"${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}\" frequencies"
+        PdBIUVT_CRVAL4=$(gethead "${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}" "CRVAL4")
+        PdBIUVT_RESTFREQ=$(gethead "${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}" "RESTFREQ")
+        if [[ x"$PdBIUVT_RESTFREQ" == x ]]; then PdBIUVT_RESTFREQ="0"; fi #<added><20170304><dzliu># 
+        echo "CRVAL4   = $PdBIUVT_CRVAL4" > "$PdBIUVT_GETHEAD"
+        echo "RESTFREQ = $PdBIUVT_RESTFREQ" >> "$PdBIUVT_GETHEAD"
+        cat "$PdBIUVT_GETHEAD"
+        #echo "BEGIN {val=(($PdBIUVT_CRVAL4)-($PdBIUVT_RESTFREQ))/((($PdBIUVT_CRVAL4)+($PdBIUVT_RESTFREQ))/2.0); print (val>0)?(val<0.001):(-val<0.001)}"
+        PdBIUVT_CHECK=$(awk "BEGIN {val=(($PdBIUVT_CRVAL4)-($PdBIUVT_RESTFREQ))/((($PdBIUVT_CRVAL4)+($PdBIUVT_RESTFREQ))/2.0); print (val>0)?(val<0.001):(-val<0.001)}")
+        if [[ $PdBIUVT_CHECK -eq 0 ]]; then
+            echo "sethead \"${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}\" RESTFREQ=$PdBIUVT_CRVAL4" > "$PdBIUVT_SETHEAD"
+                  sethead  "${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}"  RESTFREQ=$PdBIUVT_CRVAL4
+            cat "$PdBIUVT_SETHEAD"
+        fi
+        
+        
+        echo "Converting \"${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}\" to \"${PdBIUVT_SAVE[i]}.uvt\""
+        echo "FITS \"${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}\" TO \"${PdBIUVT_SAVE[i]}.uvt\" /STYLE CASA" >> "$PdBIUVT_EXE"
+        
+        
+        echo "Running @$PdBIUVT_EXE in GILDAS mapping"
+        echo "@$PdBIUVT_EXE" | mapping -nw -nl > "$PdBIUVT_LOG"
+        
+        
+        echo "Successfully saved to ${PdBIUVT_SAVE[i]}.uvt!"
+        echo "--"
+        
+    fi
+    
+done
 
-# 
-# Remove suffix
-# 
-if [[ x"$PdBIUVT_SAVE" == x*".uvt" ]]; then
-    PdBIUVT_SAVE=$(echo "$PdBIUVT_SAVE" | sed -e 's/\.uvt$//g')
-fi
-if [[ x"$PdBIUVT_SAVE" == x*".UVT" ]]; then
-    PdBIUVT_SAVE=$(echo "$PdBIUVT_SAVE" | sed -e 's/\.UVT$//g')
-fi
-
-# 
-# Backup existing output file
-# 
-if [[ -f "$PdBIUVT_SAVE.uvt" ]]; then
-    echo "Warning! Found existing \"$PdBIUVT_SAVE.uvt\"! Backup as \"$PdBIUVT_SAVE.uvt.backup\"!"
-    mv "$PdBIUVT_SAVE.uvt" "$PdBIUVT_SAVE.uvt.backup"
-fi
 
 
 
-# 
-# Deal with the input uvfits file
-# Output to mapping script
-# "$PdBIUVT_SAVE.uvt.import.uvfits.script"
-# 
-PdBIUVT_EXE="$PdBIUVT_SAVE.uvt.import.uvfits.script"
-PdBIUVT_LOG="$PdBIUVT_SAVE.uvt.import.uvfits.log"
-PdBIUVT_INI="$PdBIUVT_SAVE.uvt.import.uvfits.init"
-PdBIUVT_GETHEAD="$PdBIUVT_SAVE.uvt.import.uvfits.gethead"
-PdBIUVT_SETHEAD="$PdBIUVT_SAVE.uvt.import.uvfits.sethead"
-
-echo "" >  "$PdBIUVT_EXE"
-
-echo "Checking \"$PdBIUVT_NAME.$PdBIUVT_TYPE\" frequencies"
-PdBIUVT_CRVAL4=$(gethead "$PdBIUVT_NAME.$PdBIUVT_TYPE" "CRVAL4")
-PdBIUVT_RESTFREQ=$(gethead "$PdBIUVT_NAME.$PdBIUVT_TYPE" "RESTFREQ")
-if [[ x"$PdBIUVT_RESTFREQ" == x ]]; then PdBIUVT_RESTFREQ="0"; fi #<added><20170304><dzliu># 
-echo "CRVAL4   = $PdBIUVT_CRVAL4" > "$PdBIUVT_GETHEAD"
-echo "RESTFREQ = $PdBIUVT_RESTFREQ" >> "$PdBIUVT_GETHEAD"
-cat "$PdBIUVT_GETHEAD"
-#echo "BEGIN {val=(($PdBIUVT_CRVAL4)-($PdBIUVT_RESTFREQ))/((($PdBIUVT_CRVAL4)+($PdBIUVT_RESTFREQ))/2.0); print (val>0)?(val<0.001):(-val<0.001)}"
-PdBIUVT_CHECK=$(awk "BEGIN {val=(($PdBIUVT_CRVAL4)-($PdBIUVT_RESTFREQ))/((($PdBIUVT_CRVAL4)+($PdBIUVT_RESTFREQ))/2.0); print (val>0)?(val<0.001):(-val<0.001)}")
-if [[ $PdBIUVT_CHECK -eq 0 ]]; then
-    echo "sethead \"$PdBIUVT_NAME.$PdBIUVT_TYPE\" RESTFREQ=$PdBIUVT_CRVAL4" > "$PdBIUVT_SETHEAD"
-          sethead  "$PdBIUVT_NAME.$PdBIUVT_TYPE"  RESTFREQ=$PdBIUVT_CRVAL4
-    cat "$PdBIUVT_SETHEAD"
-fi
-
-
-echo "Converting \"$PdBIUVT_NAME.$PdBIUVT_TYPE\" to \"$PdBIUVT_SAVE.uvt\""
-echo "FITS \"$PdBIUVT_NAME.$PdBIUVT_TYPE\" TO \"$PdBIUVT_SAVE.uvt\" /STYLE CASA" >> "$PdBIUVT_EXE"
-
-
-echo "Running @$PdBIUVT_EXE in GILDAS mapping"
-echo "@$PdBIUVT_EXE" | mapping > "$PdBIUVT_LOG"
-#echo "header $PdBIUVT_NAME.uvt" | mapping > "$PdBIUVT_SAVE.uvt.header.txt"
 
 
 
-echo "Done!"
+
+
+
+
+
+
+
+
 
 
diff --git a/bin/pdbi-uvt-go-merge b/bin/pdbi-uvt-go-merge
--- a/bin/pdbi-uvt-go-merge
+++ b/bin/pdbi-uvt-go-merge
@@ -3,196 +3,220 @@
 # Input RA Dec
 # Output spec & uv_average
 # 
-PdBIUVT_NAME=()
-PdBIUVT_SAVE=""
-PdBIUVT_KEEP_FILES=0
-PdBIUVT_WEIGHT=() #<added><20170329>#
-PdBIUVT_FACTOR=() #<added><20170329># 
-PdBIUVT_CONTINUUM_MODE=0 #<added><20170329># 
-# LANG
-LANG=C
-
+# Last update:
+#    2017-03-30 using "pdbi-uvt-core-arg-v5"
+# 
+# 
 
 
 
 # 
-# Read input parameters
+# Uage
 # 
-PdBIUVT_GOOD=0; if [[ "$#" -gt 0 ]]; then PdBIUVT_GOOD=1; fi
-PdBIUVT_RPAR=""
-while [[ "$#" -gt 0 ]]; do
-    #echo $1 "$#"
-    case $1 in
-          "-save") if [[ "$#" -lt 2 ]]; then PdBIUVT_GOOD=0; break; fi; shift; PdBIUVT_RPAR=""; PdBIUVT_SAVE="$1";;
-           "-out") if [[ "$#" -lt 2 ]]; then PdBIUVT_GOOD=0; break; fi; shift; PdBIUVT_RPAR=""; PdBIUVT_SAVE="$1";;
-     "-keepfiles") if [[ "$#" -lt 1 ]]; then PdBIUVT_GOOD=0; break; fi;        PdBIUVT_RPAR=""; PdBIUVT_KEEP_FILES=1;;
-          "-name") if [[ "$#" -lt 2 ]]; then PdBIUVT_GOOD=0; break; fi; shift; PdBIUVT_RPAR="name";;
-        "-weight") if [[ "$#" -lt 2 ]]; then PdBIUVT_GOOD=0; break; fi; shift; PdBIUVT_RPAR="weight";;
-     "-weighting") if [[ "$#" -lt 2 ]]; then PdBIUVT_GOOD=0; break; fi; shift; PdBIUVT_RPAR="weight";;
-        "-factor") if [[ "$#" -lt 2 ]]; then PdBIUVT_GOOD=0; break; fi; shift; PdBIUVT_RPAR="factor";;
-       "-scaling") if [[ "$#" -lt 2 ]]; then PdBIUVT_GOOD=0; break; fi; shift; PdBIUVT_RPAR="factor";;
-     "-continuum") if [[ "$#" -lt 1 ]]; then PdBIUVT_GOOD=0; break; fi;        PdBIUVT_RPAR=""; PdBIUVT_CONTINUUM_MODE=1;;
-    esac
-    if [[ "$PdBIUVT_RPAR" == "name" ]];  then 
-        PdBIUVT_NAME=("${PdBIUVT_NAME[@]}" "$1")
-    fi
-    if [[ "$PdBIUVT_RPAR" == "weight" ]];  then 
-        PdBIUVT_WEIGHT+=("$1")
-    fi
-    if [[ "$PdBIUVT_RPAR" == "factor" ]];  then 
-        PdBIUVT_FACTOR+=("$1")
-    fi
-    shift
-done
+usage() {
+    echo "Usage: "
+    echo "   pdbi-uvt-go-merge -name UV_TABLE_NAME_1 UV_TABLE_NAME_2 [UV_TABLE_NAME_3 [UV_TABLE_NAME_4]] -out UV_TABLE_NEW [-keep-files]"
+    echo "   pdbi-uvt-go-merge -name UV_TABLE_NAME_1 UV_TABLE_NAME_2 [UV_TABLE_NAME_3 [UV_TABLE_NAME_4]] -out UV_TABLE_NEW [-keep-files] [-weight 0.5 0.5 1.0 1.0]"
+    echo "   pdbi-uvt-go-merge -name UV_TABLE_NAME_1 UV_TABLE_NAME_2 [UV_TABLE_NAME_3 [UV_TABLE_NAME_4]] -out UV_TABLE_NEW [-keep-files] [-factor 0.5 0.5 1.0 1.0]"
+    echo "   pdbi-uvt-go-merge -name UV_TABLE_NAME_1 UV_TABLE_NAME_2 [UV_TABLE_NAME_3 [UV_TABLE_NAME_4]] -out UV_TABLE_NEW [-keep-files] [-continuum-mode]"
+    echo ""
+}
+
+
+
+# 
+# SOURCE pdbi-uvt-core-arg
+# 
+if [[ -f $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5" ]]; then
+    source $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5" "$@"
+else
+    echo ""
+    echo "Error! Could not find \""$(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5\"!"
+    echo ""
+    exit 1
+fi
+
+
+
+# 
+# Check input parameters -- uvt file name
+# 
+if [[ ${#PdBIUVT_NAME[@]} -le 1 ]]; then
+    usage; exit
+fi
+
+
+
 # 
 # Make sure weighting array has the same dimension as the name array
 # 
-while [[ ${#PdBIUVT_WEIGHT[@]} -lt ${#PdBIUVT_NAME[@]} ]]; do
-    PdBIUVT_WEIGHT+=("1.0")
+while [[ ${#PdBIUVT_UVMERGE_WEIGHT[@]} -lt ${#PdBIUVT_NAME[@]} ]]; do
+    PdBIUVT_UVMERGE_WEIGHT+=("1.0")
 done
-while [[ ${#PdBIUVT_FACTOR[@]} -lt ${#PdBIUVT_NAME[@]} ]]; do
-    PdBIUVT_FACTOR+=("1.0")
+while [[ ${#PdBIUVT_UVMERGE_FACTOR[@]} -lt ${#PdBIUVT_NAME[@]} ]]; do
+    PdBIUVT_UVMERGE_FACTOR+=("1.0")
 done
-# 
-# Check input parameters -- if not passed then print usage and exit
-# 
-if [[ $PdBIUVT_GOOD -eq 0 ]]; then
-    echo "Usage: "
-    echo "   pdbi-uvt-go-merge -name UV_TABLE_NAME_1 UV_TABLE_NAME_2 [UV_TABLE_NAME_3 [UV_TABLE_NAME_4]] -out UV_TABLE_NEW [-keepfiles]"
-    echo "   pdbi-uvt-go-merge -name UV_TABLE_NAME_1 UV_TABLE_NAME_2 [UV_TABLE_NAME_3 [UV_TABLE_NAME_4]] -out UV_TABLE_NEW [-keepfiles] [-weight 0.5 0.5 1.0 1.0]"
-    echo "   pdbi-uvt-go-merge -name UV_TABLE_NAME_1 UV_TABLE_NAME_2 [UV_TABLE_NAME_3 [UV_TABLE_NAME_4]] -out UV_TABLE_NEW [-keepfiles] [-factor 0.5 0.5 1.0 1.0]"
-    echo "   pdbi-uvt-go-merge -name UV_TABLE_NAME_1 UV_TABLE_NAME_2 [UV_TABLE_NAME_3 [UV_TABLE_NAME_4]] -out UV_TABLE_NEW [-keepfiles] [-continuum]"
-    exit
-fi
+
+
+
 # 
 # Print input uvtable list
 # 
 echo PdBIUVT_NAME=${PdBIUVT_NAME[*]}
-echo PdBIUVT_SAVE=${PdBIUVT_SAVE}
-echo PdBIUVT_WEIGHT=${PdBIUVT_WEIGHT[*]}
-echo PdBIUVT_FACTOR=${PdBIUVT_FACTOR[*]}
+echo PdBIUVT_SAVE=${PdBIUVT_SAVE[0]}
+echo PdBIUVT_UVMERGE_WEIGHT=${PdBIUVT_UVMERGE_WEIGHT[*]}
+echo PdBIUVT_UVMERGE_FACTOR=${PdBIUVT_UVMERGE_FACTOR[*]}
+
+
+
 # 
-# Revise input parameters
+# Set default output file name
 # 
-# -- remove the suffix of the input uvtable name, and test whether the file exists
-for (( i=0; i<${#PdBIUVT_NAME[@]}; i++ )); do
-    PdBIUVT_NAME[i]=$(echo ${PdBIUVT_NAME[i]} | sed -E 's/[.]uvt$//g')
-    # check file existence
-    if [[ ! -f "${PdBIUVT_NAME[i]}.uvt" ]]; then
-        echo "Error! \"${PdBIUVT_NAME[i]}.uvt\" was not found! Exit!"
-        exit
+if [[ ${#PdBIUVT_SAVE[@]} -eq 0 ]]; then
+    PdBIUVT_SAVE+=("${PdBIUVT_NAME[0]}-Merged")
+    echo ""; echo "Warning! Output name was not given, setting to \"${PdBIUVT_SAVE[0]}.uvt\""; echo ""
+fi
+if [[ x"${PdBIUVT_SAVE[0]}" == x || x"${PdBIUVT_SAVE[0]}" == x"tmp_pdbi_uvt" ]]; then 
+    PdBIUVT_SAVE[0]="${PdBIUVT_NAME[0]}-Merged"
+    echo ""; echo "Warning! Output name was not given, setting to \"${PdBIUVT_SAVE[0]}.uvt\""; echo ""
+fi
+# 
+# Remove suffix
+# 
+if [[ x"${PdBIUVT_SAVE[0]}" == x*".uvt" ]]; then
+    PdBIUVT_SAVE[0]=$(echo "${PdBIUVT_SAVE[0]}" | sed -e 's/\.uvt$//g')
+fi
+if [[ x"${PdBIUVT_SAVE[0]}" == x*".UVT" ]]; then
+    PdBIUVT_SAVE[0]=$(echo "${PdBIUVT_SAVE[0]}" | sed -e 's/\.UVT$//g')
+fi
+# 
+# Backup existing output file
+# 
+if [[ -f "${PdBIUVT_SAVE[0]}.uvt" ]]; then
+    echo "Warning! Found existing \"${PdBIUVT_SAVE[0]}.uvt\"! Backup as \"${PdBIUVT_SAVE[0]}.uvt.backup\"!"
+    mv "${PdBIUVT_SAVE[0]}.uvt" "${PdBIUVT_SAVE[0]}.uvt.backup"
+fi
+
+
+
+# 
+# Loop each two pairs of the input uv tables, i starts from 1.
+# 
+for (( i=1; i<${#PdBIUVT_NAME[@]}; i++ )); do
+    # 
+    # if type is uvtable
+    # 
+    if [[ 1 == 1 ]]; then
+        # 
+        # loop each 2 uv table to merge
+        # 
+        # prepare gildas/mapping init and script and run
+        # 
+        if [[ $i -eq 1 ]]; then 
+        PdBIUVT_TEMP_TAB1="${PdBIUVT_NAME[i-1]}.${PdBIUVT_TYPE[i]}"
+        else
+        PdBIUVT_TEMP_TAB1="${PdBIUVT_SAVE[0]}."$((i-1))".uvt"
+        fi
+        PdBIUVT_TEMP_TAB2="${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}"
+        PdBIUVT_TEMP_TAB3="${PdBIUVT_SAVE[0]}.$i.uvt"
+        # 
+        #PdBIUVT_TEMP_WEIGHT="0.0" # note that the weight is only applied to TAB1 for each uv_merge run.
+        #for (( j=0; j<$i; j++ )); do
+        #    PdBIUVT_TEMP_WEIGHT=$(awk "BEGIN {print ($PdBIUVT_TEMP_WEIGHT)+(${PdBIUVT_UVMERGE_WEIGHT[j]});}")
+        #done
+        #PdBIUVT_TEMP_WEIGHT=$(awk "BEGIN {print ($PdBIUVT_TEMP_WEIGHT)/(${PdBIUVT_UVMERGE_WEIGHT[i]});}")
+        PdBIUVT_TEMP_WEIGHT=$(awk "BEGIN {print (${PdBIUVT_UVMERGE_WEIGHT[i-1]})/(${PdBIUVT_UVMERGE_WEIGHT[i]});}")
+        # 
+        #PdBIUVT_TEMP_FACTOR="${PdBIUVT_UVMERGE_FACTOR[i-1]}" # note that the factor is only applied to TAB1 for each uv_merge run.
+        #for (( j=$i; j<${#PdBIUVT_UVMERGE_FACTOR[@]}; j++ )); do
+        #    PdBIUVT_TEMP_FACTOR=$(awk "BEGIN {print ($PdBIUVT_TEMP_FACTOR)/(${PdBIUVT_UVMERGE_FACTOR[j]});}")
+        #done
+        PdBIUVT_TEMP_FACTOR=$(awk "BEGIN {print (${PdBIUVT_UVMERGE_FACTOR[i-1]})/(${PdBIUVT_UVMERGE_FACTOR[i]});}")
+        # 
+        #                    (w1/w2)*(a1/a2) * f1 + 1 * f2
+        # (w2/w3)*(a2/a3) * ((w1/w2)*(a1/a2) * f1 + 1 * f2) + 1 * f3
+        #=(w2/w3)*(a2/a3) *  (w1/w2)*(a1/a2) * f1
+        # 
+        # 
+        PdBIUVT_TEMP_INIT="${PdBIUVT_SAVE[0]}.$i.init"
+        PdBIUVT_TEMP_EXEC="${PdBIUVT_SAVE[0]}.$i.map"
+        PdBIUVT_TEMP_LOGT="${PdBIUVT_SAVE[0]}.$i.log"
+        echo  '! '                                                                                            >  $PdBIUVT_TEMP_INIT
+        echo  '! Task UV_MERGE'                                                                               >> $PdBIUVT_TEMP_INIT
+        echo  '!'                                                                                             >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\CHARACTER "UV table 1"                  TABLE_IN$      "'$PdBIUVT_TEMP_TAB1'"'            >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\REAL      "Weighting 1"                   WEIGHT$       ' $PdBIUVT_TEMP_WEIGHT            >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\REAL      "Multipling 1"                  FACTOR$       ' $PdBIUVT_TEMP_FACTOR            >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\CHARACTER "UV table 2"                 TABLE_REF$      "'$PdBIUVT_TEMP_TAB2'"'            >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\CHARACTER "UV table out"               TABLE_OUT$      "'$PdBIUVT_TEMP_TAB3'"'            >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\INTEGER   "Continuum Mode"                  MODE$       ' $PdBIUVT_UVMERGE_CONT_MODE      >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\GO'                                                                                       >> $PdBIUVT_TEMP_INIT
+        echo  "run uv_merge $PdBIUVT_TEMP_INIT /NOWINDOW" > $PdBIUVT_TEMP_EXEC
+        # or apply the last "-factor" if it is not 1.0
+        if [[ $i -eq $((${#PdBIUVT_NAME[@]}-1)) ]]; then 
+            if [[ $(awk "BEGIN {if((${PdBIUVT_UVMERGE_FACTOR[i]}-1.0)**2 > 1e-5) print 1; else print 0; }") -eq 1 ]]; then
+                PdBIUVT_TEMP_INIT="${PdBIUVT_SAVE[0]}.$i.apply.final.factor.init"
+                echo  '! '                                                                             >  $PdBIUVT_TEMP_INIT
+                echo  '! Task UV_MULT'                                                                 >> $PdBIUVT_TEMP_INIT
+                echo  '! '                                                                             >> $PdBIUVT_TEMP_INIT
+                echo  'TASK\CHARACTER "UV table"     UV_TABLE$      "'$PdBIUVT_TEMP_TAB3'"'            >> $PdBIUVT_TEMP_INIT
+                echo  'TASK\REAL "Multipling U"         MULTA$      ' 1                                >> $PdBIUVT_TEMP_INIT
+                echo  'TASK\REAL "Multipling V"         MULTB$      ' 1                                >> $PdBIUVT_TEMP_INIT
+                echo  'TASK\REAL "Multipling Intensity" MULTC$      ' ${PdBIUVT_UVMERGE_FACTOR[i]}     >> $PdBIUVT_TEMP_INIT
+                echo  'TASK\GO'                                                                        >> $PdBIUVT_TEMP_INIT
+                echo  "run uv_mult $PdBIUVT_TEMP_INIT /NOWINDOW" >> $PdBIUVT_TEMP_EXEC
+            fi
+        fi
+        echo -n "Merging \"$PdBIUVT_TEMP_TAB1\" and \"$PdBIUVT_TEMP_TAB2\" to \"$PdBIUVT_TEMP_TAB3\" (command: "
+        echo "@$PdBIUVT_TEMP_EXEC | mapping -nw -nl > $PdBIUVT_TEMP_LOGT)"
+        echo "@$PdBIUVT_TEMP_EXEC" | mapping -nw -nl > "$PdBIUVT_TEMP_LOGT"
+        
+        # check output 
+        if [[ ! -f "$PdBIUVT_TEMP_TAB3" ]]; then
+            echo "Error! Failed to merge \"$PdBIUVT_TEMP_TAB1\" and \"$PdBIUVT_TEMP_TAB2\" to \"$PdBIUVT_TEMP_TAB3\"!"
+            echo "Please check \"$PdBIUVT_TEMP_LOGT\"! (Maybe columns do not match?)"
+            exit
+        fi
+        
+        # clean intermediate uvt
+        if [[ $i -ge 2 ]]; then 
+            if [[ $PdBIUVT_UVMERGE_KEEP_FILE -eq 0 ]]; then
+                #echo "rm \"${PdBIUVT_SAVE[0]}.$((i-1)).\"*"
+                #rm "${PdBIUVT_SAVE[0]}.$((i-1))."*
+                echo "Deleted \"${PdBIUVT_SAVE[0]}.$((i-1)).uvt\""
+                rm "${PdBIUVT_SAVE[0]}.$((i-1)).uvt"
+            fi
+        fi
+        
+        if [[ $i -eq $((${#PdBIUVT_NAME[@]}-1)) ]]; then 
+            # copy final uvt
+            echo "Copying \"${PdBIUVT_SAVE[0]}.$i.uvt\" to \"${PdBIUVT_SAVE[0]}.uvt\""
+            cp "${PdBIUVT_SAVE[0]}.$i.uvt" "${PdBIUVT_SAVE[0]}.uvt"
+            # clean final intermediate uvt
+            if [[ $PdBIUVT_UVMERGE_KEEP_FILE -eq 0 ]]; then
+                #echo "rm \"${PdBIUVT_SAVE[0]}.$i.\"*"
+                #rm "${PdBIUVT_SAVE[0]}.$i."*
+                echo "Deleted \"${PdBIUVT_SAVE[0]}.$i.uvt\""
+                rm "${PdBIUVT_SAVE[0]}.$i.uvt"
+            fi
+        fi
+        
     fi
+    
 done
-if [[ "$PdBIUVT_SAVE" == *".uvt" ]]; then
-    PdBIUVT_SAVE=$(echo $PdBIUVT_SAVE | sed -E 's/[.]uvt$//g')
-fi
-# -- set output uvtable name, and check whether it exists
-if [[ x"$PdBIUVT_SAVE" == x"" ]]; then
-    echo "Warning! Output uv table name not defined, we will set it to be ${PdBIUVT_NAME[0]}-Merged.uvt!"
-    PdBIUVT_SAVE="${PdBIUVT_NAME[0]}-Merged"
-fi
-if [[ -f "$PdBIUVT_SAVE.uvt" ]]; then
-    echo "Warning! Found previous \"$PdBIUVT_SAVE.uvt\"! Backup as \"$PdBIUVT_SAVE.uvt.backup\"!"
-    cp "$PdBIUVT_SAVE.uvt" "$PdBIUVT_SAVE.uvt.backup"
-fi
+
+echo "Successufully saved to \"${PdBIUVT_SAVE[0]}.uvt\"!"
 
 
 
-# 
-# loop each 2 uv table to merge
-# 
-for (( PdBIUVT_ITER = 1; PdBIUVT_ITER < "${#PdBIUVT_NAME[@]}"; PdBIUVT_ITER++ )); do
-    # 
-    # prepare gildas/mapping init and script and run
-    # 
-    if [[ $PdBIUVT_ITER -eq 1 ]]; then 
-    PdBIUVT_TEMP_TAB1="${PdBIUVT_NAME[$PdBIUVT_ITER-1]}"
-    else
-    PdBIUVT_TEMP_TAB1="$PdBIUVT_SAVE".$(($PdBIUVT_ITER-1))
-    fi
-    PdBIUVT_TEMP_TAB2="${PdBIUVT_NAME[$PdBIUVT_ITER]}"
-    PdBIUVT_TEMP_TAB3="$PdBIUVT_SAVE.$PdBIUVT_ITER"
-    # remove suffix .uvt
-    PdBIUVT_TEMP_TAB1=$(echo $PdBIUVT_TEMP_TAB1 | sed -E 's/[.]uvt$//g')
-    PdBIUVT_TEMP_TAB2=$(echo $PdBIUVT_TEMP_TAB2 | sed -E 's/[.]uvt$//g')
-    PdBIUVT_TEMP_TAB3=$(echo $PdBIUVT_TEMP_TAB3 | sed -E 's/[.]uvt$//g')
-    # 
-    #PdBIUVT_TEMP_WEIGHT="0.0" # note that the weight is only applied to TAB1 for each uv_merge run.
-    #for (( j=0; j<$PdBIUVT_ITER; j++ )); do
-    #    PdBIUVT_TEMP_WEIGHT=$(awk "BEGIN {print ($PdBIUVT_TEMP_WEIGHT)+(${PdBIUVT_WEIGHT[j]});}")
-    #done
-    #PdBIUVT_TEMP_WEIGHT=$(awk "BEGIN {print ($PdBIUVT_TEMP_WEIGHT)/(${PdBIUVT_WEIGHT[PdBIUVT_ITER]});}")
-    PdBIUVT_TEMP_WEIGHT=$(awk "BEGIN {print (${PdBIUVT_WEIGHT[PdBIUVT_ITER-1]})/(${PdBIUVT_WEIGHT[PdBIUVT_ITER]});}")
-    # 
-    #PdBIUVT_TEMP_FACTOR="${PdBIUVT_FACTOR[PdBIUVT_ITER-1]}" # note that the factor is only applied to TAB1 for each uv_merge run.
-    #for (( j=$PdBIUVT_ITER; j<${#PdBIUVT_FACTOR[@]}; j++ )); do
-    #    PdBIUVT_TEMP_FACTOR=$(awk "BEGIN {print ($PdBIUVT_TEMP_FACTOR)/(${PdBIUVT_FACTOR[j]});}")
-    #done
-    PdBIUVT_TEMP_FACTOR=$(awk "BEGIN {print (${PdBIUVT_FACTOR[PdBIUVT_ITER-1]})/(${PdBIUVT_FACTOR[PdBIUVT_ITER]});}")
-    # 
-    #                    (w1/w2)*(a1/a2) * f1 + 1 * f2
-    # (w2/w3)*(a2/a3) * ((w1/w2)*(a1/a2) * f1 + 1 * f2) + 1 * f3
-    #=(w2/w3)*(a2/a3) *  (w1/w2)*(a1/a2) * f1
-    # 
-    # 
-    PdBIUVT_TEMP_INIT="$PdBIUVT_SAVE.$PdBIUVT_ITER.init"
-    PdBIUVT_TEMP_EXEC="$PdBIUVT_SAVE.$PdBIUVT_ITER.map"
-    PdBIUVT_TEMP_LOGT="$PdBIUVT_SAVE.$PdBIUVT_ITER.log"
-    echo  '! '                                                                                             > $PdBIUVT_TEMP_INIT
-    echo  '! Task UV_MERGE'                                                                               >> $PdBIUVT_TEMP_INIT
-    echo  '!'                                                                                             >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\CHARACTER "UV table 1"                  TABLE_IN$      "'$PdBIUVT_TEMP_TAB1.uvt'"'        >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\REAL      "Weighting 1"                   WEIGHT$       ' $PdBIUVT_TEMP_WEIGHT            >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\REAL      "Multipling 1"                  FACTOR$       ' $PdBIUVT_TEMP_FACTOR            >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\CHARACTER "UV table 2"                 TABLE_REF$      "'$PdBIUVT_TEMP_TAB2.uvt'"'        >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\CHARACTER "UV table out"               TABLE_OUT$      "'$PdBIUVT_TEMP_TAB3.uvt'"'        >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\INTEGER   "Continuum Mode"                  MODE$       ' $PdBIUVT_CONTINUUM_MODE         >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\GO'                                                                                       >> $PdBIUVT_TEMP_INIT
-    echo  "run uv_merge $PdBIUVT_TEMP_INIT /NOWINDOW" > $PdBIUVT_TEMP_EXEC
-    # or apply the last "-factor" if it is not 1.0
-    if [[ $PdBIUVT_ITER -eq $((${#PdBIUVT_NAME[@]}-1)) ]]; then 
-        if [[ $(awk "BEGIN {if((${PdBIUVT_FACTOR[PdBIUVT_ITER]}-1.0)**2 > 1e-5) print 1; else print 0; }") -eq 1 ]]; then
-            PdBIUVT_TEMP_INIT="$PdBIUVT_SAVE.$PdBIUVT_ITER.apply.final.factor.init"
-            echo  '! '                                                                              > $PdBIUVT_TEMP_INIT
-            echo  '! Task UV_MULT'                                                                 >> $PdBIUVT_TEMP_INIT
-            echo  '! '                                                                             >> $PdBIUVT_TEMP_INIT
-            echo  'TASK\CHARACTER "UV table"     UV_TABLE$      "'$PdBIUVT_TEMP_TAB3.uvt'"'        >> $PdBIUVT_TEMP_INIT
-            echo  'TASK\REAL "Multipling U"         MULTA$      ' 1                                >> $PdBIUVT_TEMP_INIT
-            echo  'TASK\REAL "Multipling V"         MULTB$      ' 1                                >> $PdBIUVT_TEMP_INIT
-            echo  'TASK\REAL "Multipling Intensity" MULTC$      ' ${PdBIUVT_FACTOR[PdBIUVT_ITER]}  >> $PdBIUVT_TEMP_INIT
-            echo  'TASK\GO'                                                                        >> $PdBIUVT_TEMP_INIT
-            echo  "run uv_mult $PdBIUVT_TEMP_INIT /NOWINDOW" >> $PdBIUVT_TEMP_EXEC
-        fi
-    fi
-    echo  "@$PdBIUVT_TEMP_EXEC  |  mapping  > ""$PdBIUVT_TEMP_LOGT"
-    echo  "@$PdBIUVT_TEMP_EXEC" |  mapping  >  "$PdBIUVT_TEMP_LOGT"
-    
-    # clean intermediate uvt
-    if [[ $PdBIUVT_ITER -ge 2 ]]; then 
-        if [[ $PdBIUVT_KEEP_FILES -eq 0 ]]; then
-            #echo "rm \"$PdBIUVT_SAVE.$(($PdBIUVT_ITER-1)).\"*"
-            #rm "$PdBIUVT_SAVE.$(($PdBIUVT_ITER-1))."*
-            echo "rm \"$PdBIUVT_SAVE.$(($PdBIUVT_ITER-1)).uvt\""
-            rm "$PdBIUVT_SAVE.$(($PdBIUVT_ITER-1)).uvt"
-        fi
-    fi
-    
-    if [[ $PdBIUVT_ITER -eq $((${#PdBIUVT_NAME[@]}-1)) ]]; then 
-        # copy final uvt
-        echo "cp \"$PdBIUVT_SAVE.$PdBIUVT_ITER.uvt\" \"$PdBIUVT_SAVE.uvt\""
-        cp "$PdBIUVT_SAVE.$PdBIUVT_ITER.uvt" "$PdBIUVT_SAVE.uvt"
-        # clean final intermediate uvt
-        if [[ $PdBIUVT_KEEP_FILES -eq 0 ]]; then
-            #echo "rm \"$PdBIUVT_SAVE.$PdBIUVT_ITER.\"*"
-            #rm "$PdBIUVT_SAVE.$PdBIUVT_ITER."*
-            echo "rm \"$PdBIUVT_SAVE.$PdBIUVT_ITER.uvt\""
-            rm "$PdBIUVT_SAVE.$PdBIUVT_ITER.uvt"
-        fi
-    fi
-    
-done
 
-echo "Successufully saved to $PdBIUVT_SAVE.uvt"
+
+
+
+
+
+
+
 
 
 
diff --git a/bin/pdbi-uvt-go-shift b/bin/pdbi-uvt-go-shift
--- a/bin/pdbi-uvt-go-shift
+++ b/bin/pdbi-uvt-go-shift
@@ -4,7 +4,8 @@
 # Output uv_shift-ed uvtable
 # pdbi-uvt-go-shift -name split_GN11_spw38.uvt -radec 12:36:27.552 62:12:17.81
 # 
-#    2017-03-30 using "pdbi-uvt-core-arg-v4"
+# Last update:
+#    2017-03-30 using "pdbi-uvt-core-arg-v5"
 # 
 # 
 
@@ -21,21 +22,16 @@ usage() {
 
 
 
-#
-# readlink
 # 
-PdBIUVT_DIR=$(dirname $(perl -MCwd -e 'print Cwd::abs_path shift' "${BASH_SOURCE[0]}"))
-
-
-
+# SOURCE pdbi-uvt-core-arg
 # 
-# Read input parameters by calling "pdbi-uvt-core-arg"
-# 
-if [[ -f "$PdBIUVT_DIR/pdbi-uvt-core-arg-v4" ]]; then
-    source "$PdBIUVT_DIR/pdbi-uvt-core-arg-v4" "$@"
+if [[ -f $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5" ]]; then
+    source $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5" "$@"
 else
-    echo ""; echo "Error! Could not find \"$PdBIUVT_DIR/pdbi-uvt-core-arg-v4\"! Please contact software supplier!"; echo ""
-    exit
+    echo ""
+    echo "Error! Could not find \""$(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5\"!"
+    echo ""
+    exit 1
 fi
 
 
@@ -49,151 +45,106 @@ fi
 
 
 
-
-
-
-
-
-
-
-
 # 
-# Set default output file as
-# "${PdBIUVT_SAVE}-Shifted.uvt"
+# Loop input uv tables
 # 
 for (( i = 0; i < "${#PdBIUVT_NAME[@]}"; i++ )); do
-    if [[ ${#PdBIUVT_SAVE[@]} -le $i ]]; then
-        PdBIUVT_SAVE+=("${PdBIUVT_NAME[i]}-Shifted")
-    fi
-    if [[ x"${PdBIUVT_SAVE[i]}" == x || x"${PdBIUVT_SAVE[i]}" == x"tmp_pdbi_uvt" ]]; then 
-        PdBIUVT_SAVE[i]="${PdBIUVT_NAME[i]}-Shifted"
-        echo ""; echo "Warning! Output name was not given for the input uvtable \"${PdBIUVT_NAME[i]}\", setting to \"${PdBIUVT_SAVE[i]}.uvt\""; echo ""
-    fi
     # 
-    # Remove suffix
+    # if type is uvtable
     # 
-    if [[ x"${PdBIUVT_SAVE[i]}" == x*".uvt" ]]; then
-        PdBIUVT_SAVE[i]=$(echo "${PdBIUVT_SAVE[i]}" | sed -e 's/\.uvt$//g')
-    fi
-    if [[ x"${PdBIUVT_SAVE[i]}" == x*".UVT" ]]; then
-        PdBIUVT_SAVE[i]=$(echo "${PdBIUVT_SAVE[i]}" | sed -e 's/\.UVT$//g')
-    fi
-    # 
-    # Backup existing output file
-    # 
-    if [[ -f "${PdBIUVT_SAVE[i]}.uvt" ]]; then
-        echo "Warning! Found existing \"${PdBIUVT_SAVE[i]}.uvt\"! Backup as \"${PdBIUVT_SAVE[i]}.uvt.backup\"!"
-        mv "${PdBIUVT_SAVE[i]}.uvt" "${PdBIUVT_SAVE[i]}.uvt.backup"
-    fi
-done
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-# 
-# Print input uvtable list
-# 
-echo PdBIUVT_NAME=${PdBIUVT_NAME[*]}
-echo PdBIUVT_SAVE=${PdBIUVT_SAVE[*]}
-# 
-# Revise input parameters
-# 
-for (( PdBIUVT_ITER = 0; PdBIUVT_ITER < "${#PdBIUVT_NAME[@]}"; PdBIUVT_ITER++ )); do
-    # -- remove the suffix of the input uvtable name, and test whether the file exists
-    if [[ "${PdBIUVT_NAME[$PdBIUVT_ITER]}" == *".uvt" ]]; then
-        PdBIUVT_NAME[$PdBIUVT_ITER]=$(echo "${PdBIUVT_NAME[$PdBIUVT_ITER]}" | sed -e 's/[.]uvt$//g')
-    fi
-    if [[ ! -f "${PdBIUVT_NAME[$PdBIUVT_ITER]}.uvt" ]]; then
-        echo "Error! \"${PdBIUVT_NAME[$PdBIUVT_ITER]}.uvt\" was not found! Exit!"
-        exit
-    fi
-done
-## -- convert RA DEC format
-#if [[ "$PdBIUVT_MAP_RA" != *":"*":"* ]]; then
-#    echo "Error! Please give RA Dec in sexagesimal format!"
-#    exit 1
-#fi
-#if [[ "$PdBIUVT_MAP_DEC" != *":"*":"* ]]; then
-#    echo "Error! Please give RA Dec in sexagesimal format!"
-#    exit 1
-#fi
-
-
-
-
-
-
-
-
-
-
-# 
-# loop each uv table to run uv_shift
-# 
-for (( PdBIUVT_ITER = 0; PdBIUVT_ITER < "${#PdBIUVT_NAME[@]}"; PdBIUVT_ITER++ )); do
-    # 
-    # check input radec
-    # 
-    if [[ ${#PdBIUVT_RANX_OBJT[@]} -le $PdBIUVT_ITER ]]; then
-        PdBIUVT_MAP_RA="${PdBIUVT_RANX_OBJT[${#PdBIUVT_RANX_OBJT[@]}-1]}"
-        PdBIUVT_MAP_DEC="${PdBIUVT_DECX_OBJT[${#PdBIUVT_DECX_OBJT[@]}-1]}"
-    else
-        PdBIUVT_MAP_RA="${PdBIUVT_RANX_OBJT[$PdBIUVT_ITER]}"
-        PdBIUVT_MAP_DEC="${PdBIUVT_DECX_OBJT[$PdBIUVT_ITER]}"
-    fi
-    if [[ ${#PdBIUVT_OBJ_ANGLE[@]} -gt 0 ]]; then
-        if [[ ${#PdBIUVT_OBJ_ANGLE[@]} -le $PdBIUVT_ITER ]]; then
-            PdBIUVT_MAP_ANGLE="${PdBIUVT_OBJ_ANGLE[${#PdBIUVT_OBJ_ANGLE[@]}-1]}"
-        else
-            PdBIUVT_MAP_ANGLE="${PdBIUVT_OBJ_ANGLE[$PdBIUVT_ITER]}"
+    if [[ ${PdBIUVT_TYPE[i]} == "uvt" || ${PdBIUVT_TYPE[i]} == "UVT" ]]; then
+        # 
+        # Set default output file name
+        # 
+        if [[ ${#PdBIUVT_SAVE[@]} -le $i ]]; then
+            PdBIUVT_SAVE+=("${PdBIUVT_NAME[i]}-Shifted")
         fi
-    else
-        PdBIUVT_MAP_ANGLE="0"
+        if [[ x"${PdBIUVT_SAVE[i]}" == x || x"${PdBIUVT_SAVE[i]}" == x"tmp_pdbi_uvt" ]]; then 
+            PdBIUVT_SAVE[i]="${PdBIUVT_NAME[i]}-Shifted"
+            echo ""; echo "Warning! Output name was not given for the input uvtable \"${PdBIUVT_NAME[i]}\", setting to \"${PdBIUVT_SAVE[i]}.uvt\""; echo ""
+        fi
+        # 
+        # Remove suffix
+        # 
+        if [[ x"${PdBIUVT_SAVE[i]}" == x*".uvt" ]]; then
+            PdBIUVT_SAVE[i]=$(echo "${PdBIUVT_SAVE[i]}" | sed -e 's/\.uvt$//g')
+        fi
+        if [[ x"${PdBIUVT_SAVE[i]}" == x*".UVT" ]]; then
+            PdBIUVT_SAVE[i]=$(echo "${PdBIUVT_SAVE[i]}" | sed -e 's/\.UVT$//g')
+        fi
+        # 
+        # Backup existing output file
+        # 
+        if [[ -f "${PdBIUVT_SAVE[i]}.uvt" ]]; then
+            echo "Warning! Found existing \"${PdBIUVT_SAVE[i]}.uvt\"! Backup as \"${PdBIUVT_SAVE[i]}.uvt.backup\"!"
+            mv "${PdBIUVT_SAVE[i]}.uvt" "${PdBIUVT_SAVE[i]}.uvt.backup"
+        fi
+        # 
+        # check input radec
+        # 
+        if [[ ${#PdBIUVT_RANX_OBJT[@]} -le $i ]]; then
+            PdBIUVT_MAP_RA="${PdBIUVT_RANX_OBJT[${#PdBIUVT_RANX_OBJT[@]}-1]}" # repeat the last input radec pair if the input radec pair number is less than uvtable number
+            PdBIUVT_MAP_DEC="${PdBIUVT_DECX_OBJT[${#PdBIUVT_DECX_OBJT[@]}-1]}" # repeat the last input radec pair if the input radec pair number is less than uvtable number
+        else
+            PdBIUVT_MAP_RA="${PdBIUVT_RANX_OBJT[i]}"
+            PdBIUVT_MAP_DEC="${PdBIUVT_DECX_OBJT[i]}"
+        fi
+        if [[ ${#PdBIUVT_OBJ_ANGLE[@]} -gt 0 ]]; then
+            if [[ ${#PdBIUVT_OBJ_ANGLE[@]} -le $i ]]; then
+                PdBIUVT_MAP_ANGLE="${PdBIUVT_OBJ_ANGLE[${#PdBIUVT_OBJ_ANGLE[@]}-1]}"
+            else
+                PdBIUVT_MAP_ANGLE="${PdBIUVT_OBJ_ANGLE[i]}"
+            fi
+        else
+            PdBIUVT_MAP_ANGLE="0"
+        fi
+        # 
+        # prepare gildas/mapping init and script and run
+        # 
+        # "let name ${PdBIUVT_NAME[i]}"
+        # "let map_ra ${PdBIUVT_MAP_RA}"
+        # "let map_dec ${PdBIUVT_MAP_DEC}"
+        # 
+        #PdBIUVT_TEMP_INIT="${PdBIUVT_SAVE[i]}.init"
+        #PdBIUVT_TEMP_EXEC="${PdBIUVT_SAVE[i]}.map"
+        #PdBIUVT_TEMP_LOGT="${PdBIUVT_SAVE[i]}.log"
+        PdBIUVT_TEMP_INIT="${PdBIUVT_SAVE[i]}.uvt.uv_shift.init"
+        PdBIUVT_TEMP_EXEC="${PdBIUVT_SAVE[i]}.uvt.uv_shift.script"
+        PdBIUVT_TEMP_LOGT="${PdBIUVT_SAVE[i]}.uvt.uv_shift.log"
+        # 
+        # copy uv table because uv_shift operates on uv table and do not write new uv table
+        cp "${PdBIUVT_NAME[i]}.uvt" "${PdBIUVT_SAVE[i]}.uvt"
+        # 
+        echo  '! '                                                                                                             > $PdBIUVT_TEMP_INIT
+        echo  '! Task UV_SHIFT'                                                                                               >> $PdBIUVT_TEMP_INIT
+        echo  '!'                                                                                                             >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\CHARACTER "UV table 1"                             UVTABLE$      "'${PdBIUVT_SAVE[i]}.uvt'"'              >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\LOGICAL   "Offset mode YES or Absolute mode NO"   RELATIVE$       ' NO                                    >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\REAL      "Offset mode offset by radians"           OFFSET$[2]    ' 0 0                                   >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\CHARACTER "Absolute mode RA center"              RA_CENTER$      "'$PdBIUVT_MAP_RA'"'                     >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\CHARACTER "Absolute mode DEC center"            DEC_CENTER$      "'$PdBIUVT_MAP_DEC'"'                    >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\REAL      "Angle"                                    ANGLE$       '$PdBIUVT_MAP_ANGLE                     >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\LOGICAL   "Accuracy"                               PRECISE$       ' YES                                   >> $PdBIUVT_TEMP_INIT
+        echo  'TASK\GO'                                                                                                       >> $PdBIUVT_TEMP_INIT
+        echo  "run uv_shift $PdBIUVT_TEMP_INIT /NOWINDOW" > $PdBIUVT_TEMP_EXEC
+        echo  "@$PdBIUVT_TEMP_EXEC | mapping -nw -nl > $PdBIUVT_TEMP_LOGT"
+        echo  "@$PdBIUVT_TEMP_EXEC" | mapping -nw -nl >  "$PdBIUVT_TEMP_LOGT"
+        # 
+        # Check final output
+        # 
+        if [[ -f "${PdBIUVT_SAVE[i]}.uvt" ]]; then
+            echo "Successufully saved to \"${PdBIUVT_SAVE[i]}.uvt\"!"
+            echo "--"
+            if [[ -f "$PdBIUVT_TEMP_LOGT" ]]; then
+                rm "$PdBIUVT_TEMP_LOGT"
+            fi
+        else
+            echo "Error! Failed to run GILDAS MAPPING UV_SUBTRACT and output \"${PdBIUVT_SAVE[i]}.uvt\"!"
+            echo "Please check \"$PdBIUVT_TEMP_LOGT\"!"
+            exit 1
+        fi
+        
     fi
-    # 
-    # prepare gildas/mapping init and script and run
-    # 
-    # "let name ${PdBIUVT_NAME[$PdBIUVT_ITER]}"
-    # "let map_ra ${PdBIUVT_MAP_RA}"
-    # "let map_dec ${PdBIUVT_MAP_DEC}"
-    # 
-    #PdBIUVT_TEMP_INIT="${PdBIUVT_SAVE[$PdBIUVT_ITER]}.init"
-    #PdBIUVT_TEMP_EXEC="${PdBIUVT_SAVE[$PdBIUVT_ITER]}.map"
-    #PdBIUVT_TEMP_LOGT="${PdBIUVT_SAVE[$PdBIUVT_ITER]}.log"
-    PdBIUVT_TEMP_INIT="${PdBIUVT_SAVE[$PdBIUVT_ITER]}.uvt.uv_shift.init"
-    PdBIUVT_TEMP_EXEC="${PdBIUVT_SAVE[$PdBIUVT_ITER]}.uvt.uv_shift.script"
-    PdBIUVT_TEMP_LOGT="${PdBIUVT_SAVE[$PdBIUVT_ITER]}.uvt.uv_shift.log"
-    # 
-    # copy uv table because uv_shift operates on uv table and do not write new uv table
-    cp "${PdBIUVT_NAME[$PdBIUVT_ITER]}.uvt" "${PdBIUVT_SAVE[$PdBIUVT_ITER]}.uvt"
-    # 
-    echo  '! '                                                                                                             > $PdBIUVT_TEMP_INIT
-    echo  '! Task UV_SHIFT'                                                                                               >> $PdBIUVT_TEMP_INIT
-    echo  '! 6 parameters needed for all functions'                                                                       >> $PdBIUVT_TEMP_INIT
-    echo  '!'                                                                                                             >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\CHARACTER "UV table 1"                             UVTABLE$      "'${PdBIUVT_SAVE[$PdBIUVT_ITER]}.uvt'"'  >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\LOGICAL   "Offset mode YES or Absolute mode NO"   RELATIVE$       ' NO                                    >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\REAL      "Offset mode offset by radians"           OFFSET$[2]    ' 0 0                                   >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\CHARACTER "Absolute mode RA center"              RA_CENTER$      "'$PdBIUVT_MAP_RA'"'                     >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\CHARACTER "Absolute mode DEC center"            DEC_CENTER$      "'$PdBIUVT_MAP_DEC'"'                    >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\REAL      "Angle"                                    ANGLE$       '$PdBIUVT_MAP_ANGLE                     >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\LOGICAL   "Accuracy"                               PRECISE$       ' YES                                   >> $PdBIUVT_TEMP_INIT
-    echo  'TASK\GO'                                                                                                       >> $PdBIUVT_TEMP_INIT
-    echo  "run uv_shift $PdBIUVT_TEMP_INIT /NOWINDOW"  >> $PdBIUVT_TEMP_EXEC
-    echo  "@$PdBIUVT_TEMP_EXEC  |  mapping  > ""$PdBIUVT_TEMP_LOGT"
-    echo  "@$PdBIUVT_TEMP_EXEC" |  mapping  >  "$PdBIUVT_TEMP_LOGT"
-    
-    echo "Successufully saved to ${PdBIUVT_SAVE[$PdBIUVT_ITER]}.uvt"
     
 done
 
diff --git a/bin/pdbi-uvt-go-splitpolar b/bin/pdbi-uvt-go-splitpolar
--- a/bin/pdbi-uvt-go-splitpolar
+++ b/bin/pdbi-uvt-go-splitpolar
@@ -8,6 +8,7 @@
 #    2016-07-10 <TODO> what if multi-stokes?
 #    2017-02-19 rewritten, beautified, used "pdbi-uvt-core-arg"
 #    2017-03-30 using "pdbi-uvt-core-arg-v4"
+#    2017-03-30 using "pdbi-uvt-core-arg-v5"
 # 
 # 
 
@@ -18,27 +19,22 @@
 # 
 usage() {
     echo "Usage: "
-    echo "  pdbi-uvt-go-splitpolar -name PdBIUVT_NAME.uvt -out PdBIUVT_SAVE.uvt"
+    echo "  pdbi-uvt-go-splitpolar -name NAME.uvt -out SAVE.uvt"
     echo ""
 }
 
 
 
-#
-# readlink
 # 
-PdBIUVT_DIR=$(dirname $(perl -MCwd -e 'print Cwd::abs_path shift' "${BASH_SOURCE[0]}"))
-
-
-
+# SOURCE pdbi-uvt-core-arg
 # 
-# Read input parameters by calling "pdbi-uvt-core-arg"
-# 
-if [[ -f "$PdBIUVT_DIR/pdbi-uvt-core-arg-v4" ]]; then
-    source "$PdBIUVT_DIR/pdbi-uvt-core-arg-v4" "$@"
+if [[ -f $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5" ]]; then
+    source $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5" "$@"
 else
-    echo ""; echo "Error! Could not find \"$PdBIUVT_DIR/pdbi-uvt-core-arg-v4\"! Please contact software supplier!"; echo ""
-    exit
+    echo ""
+    echo "Error! Could not find \""$(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5\"!"
+    echo ""
+    exit 1
 fi
 
 
@@ -46,87 +42,114 @@ fi
 # 
 # Check input parameters -- uvt file name
 # 
-if [[ x"$PdBIUVT_NAME" == x ]]; then
+if [[ ${#PdBIUVT_NAME[@]} -eq 0 ]]; then
     usage; exit
 fi
 
 
 
-
-
-
-
-
-
-
-
 # 
-# Set default output file as
-# "$PdBIUVT_SAVE.uvt.go.uvmap.eps"
+# Loop input uv tables
 # 
-if [[ x"$PdBIUVT_SAVE" == x || x"$PdBIUVT_SAVE" == x"tmp_pdbi_uvt" ]]; then 
-    PdBIUVT_SAVE="${PdBIUVT_NAME}_SP"
-    echo ""; echo "Warning! Output name was not given, setting to \"$PdBIUVT_SAVE.uvt\""; echo ""
-fi
+for (( i = 0; i < "${#PdBIUVT_NAME[@]}"; i++ )); do
+    # 
+    # if type is uvtable
+    # 
+    if [[ ${PdBIUVT_TYPE[i]} == "uvt" || ${PdBIUVT_TYPE[i]} == "UVT" ]]; then
+        # 
+        # Set default output file name
+        # 
+        if [[ ${#PdBIUVT_SAVE[@]} -le $i ]]; then
+            PdBIUVT_SAVE+=("${PdBIUVT_NAME[i]}_SP")
+        fi
+        if [[ x"${PdBIUVT_SAVE[i]}" == x || x"${PdBIUVT_SAVE[i]}" == x"tmp_pdbi_uvt" ]]; then 
+            PdBIUVT_SAVE[i]="${PdBIUVT_NAME[i]}_SP"
+            echo ""; echo "Warning! Output name was not given for the input uvtable \"${PdBIUVT_NAME[i]}\", setting to \"${PdBIUVT_SAVE[i]}.uvt\""; echo ""
+        fi
+        # 
+        # Remove suffix
+        # 
+        if [[ x"${PdBIUVT_SAVE[i]}" == x*".uvt" ]]; then
+            PdBIUVT_SAVE[i]=$(echo "${PdBIUVT_SAVE[i]}" | sed -e 's/\.uvt$//g')
+        fi
+        if [[ x"${PdBIUVT_SAVE[i]}" == x*".UVT" ]]; then
+            PdBIUVT_SAVE[i]=$(echo "${PdBIUVT_SAVE[i]}" | sed -e 's/\.UVT$//g')
+        fi
+        # 
+        # Backup existing output file
+        # 
+        if [[ -f "${PdBIUVT_SAVE[i]}.uvt" ]]; then
+            echo "Warning! Found existing \"${PdBIUVT_SAVE[i]}.uvt\"! Backup as \"${PdBIUVT_SAVE[i]}.uvt.backup\"!"
+            mv "${PdBIUVT_SAVE[i]}.uvt" "${PdBIUVT_SAVE[i]}.uvt.backup"
+        fi
+        # 
+        # Deal with the input uv table file
+        # Output to mapping script
+        # "${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}.uvt.splitpolar.script"
+        # 
+        PdBIUVT_EXE="${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}.uv_splitpolar.script"
+        PdBIUVT_LOG="${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}.uv_splitpolar.log"
+        PdBIUVT_INI="${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}.uv_splitpolar.init"
+        
+        echo "Checking \"${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}\""
+        
+        if [[ ! -f "${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}.header.txt" ]]; then
+            echo "header ${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}" | mapping -nw -nl > "${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}.header.txt"
+        fi
+        
+        if [[ -f "${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}.header.txt" ]]; then
+            PdBIUVT_Stokes=$(grep "Stokes: " "${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}.header.txt" | sed -E 's/.*Stokes: *([0-9]*) *.*/\1/g')
+        else
+            echo ""; echo "Error! Failed to run \"header ${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}\" in GILDAS mapping and output \"${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}.header.txt\"!"; echo ""
+            exit 1
+        fi
+        
+        if [[ $PdBIUVT_Stokes -le 1 ]]; then
+            echo "Warning! The number of stokes in \"${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}\" is already one, no need to split and merge!"
+        else
+            echo "Splitting \"${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}\" polarizations and merging into a single polarization uv data file"
+            echo "TASK\\FILE      \"\"      INPUT\$ \"${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}\""  >  "$PdBIUVT_INI"
+            echo "TASK\\FILE      \"\"     OUTPUT\$ \"${PdBIUVT_SAVE[i]}.uvt\""                 >> "$PdBIUVT_INI"
+            echo "TASK\\CHARACTER \"\"     STOKES\$ \"NONE\""                                   >> "$PdBIUVT_INI"
+            echo "TASK\\GO"                                                                     >> "$PdBIUVT_INI"
+            echo "run uv_splitpolar $PdBIUVT_INI /NOWINDOW" > "$PdBIUVT_EXE"
+            echo "Running @$PdBIUVT_EXE in GILDAS mapping"
+            echo "@$PdBIUVT_EXE | mapping -nw -nl > $PdBIUVT_LOG"
+            echo "@$PdBIUVT_EXE" | mapping -nw -nl > "$PdBIUVT_LOG"
+            # 
+            # Check final output
+            # 
+            if [[ -f "${PdBIUVT_SAVE[i]}.uvt" ]]; then
+                echo "Successufully saved to \"${PdBIUVT_SAVE[i]}.uvt\"!"
+                echo "--"
+                if [[ -f "$PdBIUVT_LOG" ]]; then
+                    rm "$PdBIUVT_LOG"
+                fi
+            else
+                echo "Error! Failed to run GILDAS MAPPING UV_SPLITPOLAR and output \"${PdBIUVT_SAVE[i]}.uvt\"!"
+                echo "Please check \"$PdBIUVT_LOG\"!"
+                exit 1
+            fi
+        fi
+    
+    else
+        
+        echo ""; echo "Skipping \"${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}\" because it is not *.uvt or *.UVT!"; echo ""
+      
+    fi
+    
+done
 
-# 
-# Remove suffix
-# 
-if [[ x"$PdBIUVT_SAVE" == x*".uvt" ]]; then
-    PdBIUVT_SAVE=$(echo "$PdBIUVT_SAVE" | sed -e 's/\.uvt$//g')
-fi
-if [[ x"$PdBIUVT_SAVE" == x*".UVT" ]]; then
-    PdBIUVT_SAVE=$(echo "$PdBIUVT_SAVE" | sed -e 's/\.UVT$//g')
-fi
-
-# 
-# Backup existing output file
-# 
-if [[ -f "$PdBIUVT_SAVE.uvt" ]]; then
-    echo "Warning! Found existing \"$PdBIUVT_SAVE.uvt\"! Backup as \"$PdBIUVT_SAVE.uvt.backup\"!"
-    mv "$PdBIUVT_SAVE.uvt" "$PdBIUVT_SAVE.uvt.backup"
-fi
 
 
 
-# 
-# Deal with the input uvfits file
-# Output to mapping script
-# "$PdBIUVT_NAME.$PdBIUVT_TYPE.uvt.splitpolar.script"
-# 
-PdBIUVT_EXE="$PdBIUVT_NAME.$PdBIUVT_TYPE.splitpolar.script"
-PdBIUVT_LOG="$PdBIUVT_NAME.$PdBIUVT_TYPE.splitpolar.log"
-PdBIUVT_INI="$PdBIUVT_NAME.$PdBIUVT_TYPE.splitpolar.init"
-
-echo "Checking \"$PdBIUVT_NAME.$PdBIUVT_TYPE\""
-
-if [[ ! -f "$PdBIUVT_NAME.$PdBIUVT_TYPE.header.txt" ]]; then
-    echo "header $PdBIUVT_NAME.$PdBIUVT_TYPE" | mapping > "$PdBIUVT_NAME.$PdBIUVT_TYPE.header.txt"
-fi
-
-if [[ -f "$PdBIUVT_NAME.$PdBIUVT_TYPE.header.txt" ]]; then
-    PdBIUVT_Stokes=$(grep "Stokes: " "$PdBIUVT_NAME.$PdBIUVT_TYPE.header.txt" | sed -E 's/.*Stokes: *([0-9]*) *.*/\1/g')
-else
-    echo ""; echo "Error! Could not run \"header $PdBIUVT_NAME.$PdBIUVT_TYPE\" in GILDAS mapping and create \"$PdBIUVT_NAME.$PdBIUVT_TYPE.header.txt\"!"; echo ""; exit
-fi
-
-if [[ $PdBIUVT_Stokes -le 1 ]]; then
-    echo "Warning! The number of stokes in \"$PdBIUVT_NAME.$PdBIUVT_TYPE\" is already one, no need to split and merge!"
-else
-    echo "Splitting \"$PdBIUVT_NAME.$PdBIUVT_TYPE\" polarizations and merging into single data"
-    echo "TASK\\FILE      \"\"      INPUT\$ \"$PdBIUVT_NAME.$PdBIUVT_TYPE\""  >  "$PdBIUVT_INI"
-    echo "TASK\\FILE      \"\"     OUTPUT\$ \"$PdBIUVT_SAVE.uvt\""            >> "$PdBIUVT_INI"
-    echo "TASK\\CHARACTER \"\"     STOKES\$ \"NONE\""                         >> "$PdBIUVT_INI"
-    echo "TASK\\GO"                                                           >> "$PdBIUVT_INI"
-    echo "run uv_splitpolar $PdBIUVT_INI /NOWINDOW"  >  "$PdBIUVT_EXE"
-    echo "Running @$PdBIUVT_EXE in GILDAS mapping"
-    echo "@$PdBIUVT_EXE" | mapping > "$PdBIUVT_LOG"
-    echo "@$PdBIUVT_EXE" | mapping > "$PdBIUVT_LOG"
-    #echo "header $PdBIUVT_SAVE.uvt" | mapping > "$PdBIUVT_SAVE.uvt.header.txt"
-fi
 
 
 
-echo "Done!"
+
+
+
+
+
 
 
diff --git a/bin/pdbi-uvt-go-uvmap b/bin/pdbi-uvt-go-uvmap
--- a/bin/pdbi-uvt-go-uvmap
+++ b/bin/pdbi-uvt-go-uvmap
@@ -5,6 +5,7 @@
 # 
 # Last update:
 #    2017-02-19 rewritten, beautified, used "pdbi-uvt-core-arg"
+#    2017-03-30 using "pdbi-uvt-core-arg-v5"
 # 
 # 
 
@@ -21,21 +22,16 @@ usage() {
 
 
 
-#
-# readlink current dir
 # 
-PdBIUVT_DIR=$(perl -MCwd -e 'print Cwd::abs_path shift' $(dirname "${BASH_SOURCE[0]}"))
-
-
-
+# SOURCE pdbi-uvt-core-arg
 # 
-# Read input parameters by calling "pdbi-uvt-core-arg"
-# 
-if [[ -f "$PdBIUVT_DIR/pdbi-uvt-core-arg-v3" ]]; then
-    source "$PdBIUVT_DIR/pdbi-uvt-core-arg-v3" "$@"
+if [[ -f $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5" ]]; then
+    source $(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5" "$@"
 else
-    echo ""; echo "Error! Could not find \"$PdBIUVT_DIR/pdbi-uvt-core-arg\"! Please contact software supplier!"; echo ""
-    exit
+    echo ""
+    echo "Error! Could not find \""$(dirname "${BASH_SOURCE[0]}")"/pdbi-uvt-core-arg-v5\"!"
+    echo ""
+    exit 1
 fi
 
 
@@ -43,75 +39,114 @@ fi
 # 
 # Check input parameters -- uvt file name
 # 
-if [[ x"$PdBIUVT_NAME" == x ]]; then
+if [[ ${#PdBIUVT_NAME[@]} -eq 0 ]]; then
     usage; exit
 fi
 
 
 
-
-
-
-
-
-
-
-
-
-
 # 
-# Deal with the input uvt file
-# Output to mapping script
-# "$PdBIUVT_NAME.uvt.go.uvmap.script"
+# Loop input uv tables
 # 
-PdBIUVT_EXE="$PdBIUVT_NAME.$PdBIUVT_TYPE.go.uvmap.script"
-PdBIUVT_LOG="$PdBIUVT_NAME.$PdBIUVT_TYPE.go.uvmap.log"
+for (( i = 0; i < "${#PdBIUVT_NAME[@]}"; i++ )); do
+    # 
+    # if type is uvtable
+    # 
+    if [[ ${PdBIUVT_TYPE[i]} == "uvt" || ${PdBIUVT_TYPE[i]} == "UVT" ]]; then
+        # 
+        # Set default output file name
+        # 
+        if [[ ${#PdBIUVT_SAVE[@]} -le $i ]]; then
+            PdBIUVT_SAVE+=("${PdBIUVT_NAME[i]}")
+        fi
+        if [[ x"${PdBIUVT_SAVE[i]}" == x || x"${PdBIUVT_SAVE[i]}" == x"tmp_pdbi_uvt" ]]; then 
+            PdBIUVT_SAVE[i]="${PdBIUVT_NAME[i]}"
+            echo ""; echo "Warning! Output name was not given for the input uvtable \"${PdBIUVT_NAME[i]}\", setting to \"${PdBIUVT_SAVE[i]}\""; echo ""
+        fi
+        # 
+        # Remove suffix
+        # 
+        if [[ x"${PdBIUVT_SAVE[i]}" == x*".eps" ]]; then
+            PdBIUVT_SAVE[i]=$(echo "${PdBIUVT_SAVE[i]}" | sed -e 's/\.eps$//g')
+        fi
+        if [[ x"${PdBIUVT_SAVE[i]}" == x*".EPS" ]]; then
+            PdBIUVT_SAVE[i]=$(echo "${PdBIUVT_SAVE[i]}" | sed -e 's/\.EPS$//g')
+        fi
+        # 
+        # Backup existing output file
+        # 
+        if [[ -f "${PdBIUVT_SAVE[i]}.eps" ]]; then
+            echo "Warning! Found existing \"${PdBIUVT_SAVE[i]}.eps\"! Backup as \"${PdBIUVT_SAVE[i]}.eps.backup\"!"
+            mv "${PdBIUVT_SAVE[i]}.eps" "${PdBIUVT_SAVE[i]}.eps.backup"
+        fi
+        # 
+        # 
+        # Deal with the input uvt file
+        # Output to mapping script
+        # "$PdBIUVT_NAME.uvt.go.uvmap.script"
+        # 
+        PdBIUVT_EXE="${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}.uv_map.script"
+        PdBIUVT_LOG="${PdBIUVT_NAME[i]}.${PdBIUVT_TYPE[i]}.uv_map.log"
+        PdBIUVT_EPS="${PdBIUVT_SAVE[i]}"
+        
+        echo ""                                >  "$PdBIUVT_EXE"
+        echo ""                                >> "$PdBIUVT_EXE"
+        echo "let name \"${PdBIUVT_NAME[i]}\"" >> "$PdBIUVT_EXE"
+        
+        if [[ ${#PdBIUVT_SIZE[@]}     -gt 0 ]]; then echo "let size ${PdBIUVT_SIZE[0]}"          >> "$PdBIUVT_EXE"; PdBIUVT_EPS="${PdBIUVT_EPS}_FoV_"$(printf "%.0f" ${PdBIUVT_SIZE[0]})"_arcsec"; fi
+        if [[ ${#PdBIUVT_MAP_SIZE[@]} -gt 0 ]]; then echo "let map_size ${PdBIUVT_MAP_SIZE[0]}"  >> "$PdBIUVT_EXE"; fi
+        if [[ ${#PdBIUVT_MAP_CELL[@]} -gt 0 ]]; then echo "let map_cell ${PdBIUVT_MAP_CELL[0]}"  >> "$PdBIUVT_EXE"; fi
+        
+        echo "go uvmap"             >> "$PdBIUVT_EXE"
+        echo "go noise"             >> "$PdBIUVT_EXE"
+        echo "let spacing noise"    >> "$PdBIUVT_EXE"
+        echo "go view"              >> "$PdBIUVT_EXE"
+        
+        # 
+        # Overwrite or not
+        # 
+        if [[ "$PdBIUVT_OVERWRITE" == "YES" ]]; then
+            echo "hardcopy \"${PdBIUVT_EPS}.eps\" /overwrite"    >> "$PdBIUVT_EXE"
+            echo "sys \"ps2pdf -dEPSCrop ${PdBIUVT_EPS}.eps\""   >> "$PdBIUVT_EXE"
+        else
+            echo "hardcopy \"${PdBIUVT_EPS}.eps\""               >> "$PdBIUVT_EXE"
+            echo "sys \"ps2pdf -dEPSCrop ${PdBIUVT_EPS}.eps\""   >> "$PdBIUVT_EXE"
+        fi
+        
+        # 
+        # Run mapping script
+        # 
+        echo "@$PdBIUVT_EXE" | mapping -nw -nl | tee "$PdBIUVT_LOG"
+        
+        # 
+        # Check output
+        # 
+        if [[ -f "${PdBIUVT_EPS}.eps" ]]; then
+            echo "Successufully saved to \"${PdBIUVT_EPS}.eps\"!"
+            echo "--"
+            #if [[ -f "$PdBIUVT_LOG" ]]; then
+            #    rm "$PdBIUVT_LOG"
+            #fi
+        else
+            echo "Error! Failed to run GILDAS MAPPING UV_MAP and output \"${PdBIUVT_EPS}.eps\"!"
+            echo "Please check \"$PdBIUVT_LOG\"!"
+            exit 1
+        fi
+        
+    fi
+    
+done
 
-echo ""                        >  "$PdBIUVT_EXE"
-echo ""                        >> "$PdBIUVT_EXE"
-echo "let name $PdBIUVT_NAME"  >> "$PdBIUVT_EXE"
-
-i=0
-
-if [[ $i -lt ${#PdBIUVT_SIZE[@]}     ]]; then echo "let size ${PdBIUVT_SIZE[i]}"          >> "$PdBIUVT_EXE"; fi
-if [[ $i -lt ${#PdBIUVT_MAP_SIZE[@]} ]]; then echo "let map_size ${PdBIUVT_MAP_SIZE[i]}"  >> "$PdBIUVT_EXE"; fi
-if [[ $i -lt ${#PdBIUVT_MAP_CELL[@]} ]]; then echo "let map_cell ${PdBIUVT_MAP_CELL[i]}"  >> "$PdBIUVT_EXE"; fi
-
-echo "go uvmap"             >> "$PdBIUVT_EXE"
-echo "go noise"             >> "$PdBIUVT_EXE"
-echo "let spacing noise"    >> "$PdBIUVT_EXE"
-echo "go view"              >> "$PdBIUVT_EXE"
-
-# Set default output file as
-# "$PdBIUVT_NAME.uvt.go.uvmap.eps"
-if [[ x"$PdBIUVT_SAVE" == x || x"$PdBIUVT_SAVE" == x"tmp_pdbi_uvt" ]]; then 
-    PdBIUVT_SAVE="$PdBIUVT_NAME.uvt.go.uvmap.eps"
-    echo ""; echo "Warning! Output name was not given, setting to \"$PdBIUVT_SAVE\""; echo ""
-fi
-
-# Set default output file extension as eps
-if [[ x"$PdBIUVT_SAVE" != x*".eps" ]]; then
-    PdBIUVT_SAVE="$PdBIUVT_SAVE.eps"
-fi
-
-# Overwrite or not
-if [[ "$PdBIUVT_OVERWRITE" == "YES" ]]; then
-    echo "hardcopy \"$PdBIUVT_SAVE\" /overwrite"    >> "$PdBIUVT_EXE"
-    echo "sys \"ps2pdf -dEPSCrop $PdBIUVT_SAVE\""   >> "$PdBIUVT_EXE"
-else
-    echo "hardcopy \"$PdBIUVT_SAVE\""               >> "$PdBIUVT_EXE"
-    echo "sys \"ps2pdf -dEPSCrop $PdBIUVT_SAVE\""   >> "$PdBIUVT_EXE"
-fi
-
-# Run mapping script
-echo "@$PdBIUVT_EXE" | mapping | tee "$PdBIUVT_LOG"
 
 
-echo ""
-echo "Output to $PdBIUVT_SAVE"
-echo ""
 
 
-echo "Done!"
+
+
+
+
+
+
+
 
 
